/* Generated by tools/gen-assets.js. */
(function (root) { (root.NB || (root.NB = {})).ASSET_FILES = {
 "places": {},
 "cards": {},
 "portraits": {},
 "snapshots": {},
 "cinematic": {
  "intro-01": "art/cinematic/intro-01.png",
  "intro-02": "art/cinematic/intro-02.png",
  "intro-03": "art/cinematic/intro-03.png",
  "intro-04": "art/cinematic/intro-04.png",
  "intro-05": "art/cinematic/intro-05.png",
  "intro-06": "art/cinematic/intro-06.png",
  "intro-07": "art/cinematic/intro-07.png",
  "intro-08": "art/cinematic/intro-08.png",
  "intro-09": "art/cinematic/intro-09.png",
  "intro-10": "art/cinematic/intro-10.png",
  "intro-11": "art/cinematic/intro-11.png"
 }
}; })(typeof window !== "undefined" ? window : globalThis);
