/* Wrenfold — generated by tools/gen-config.js from plan/. Do not edit by hand. */
(function (root) {
  "use strict";
  var NB = root.NB || (root.NB = {});
  NB.plan = {
 "startVars": {
  "name": "Alex",
  "mc_kind": "witch",
  "they": "she",
  "them": "her",
  "their": "her",
  "theyre": "she's",
  "look_skin": 0,
  "look_form": 0,
  "thimble": false,
  "job": "calls",
  "brought": "",
  "told_nana": false,
  "steam": true,
  "date": "2026-09-10",
  "ch": 1,
  "nerve": 20,
  "wit": 20,
  "heart": 20,
  "flame": 20,
  "kindling": 0,
  "chill": 0,
  "house": "",
  "cas_house": "rookhallow",
  "pts_larkspire": 0,
  "pts_owlcombe": 0,
  "pts_heronmere": 0,
  "pts_rookhallow": 0,
  "familiar": "",
  "fam_name": "",
  "wand_wood": "",
  "wand_core": "",
  "best_subject": "",
  "glimmer": false,
  "detentions": 0,
  "kindler_known": false,
  "told_toby": false,
  "told_rowan": false,
  "told_imogen": false,
  "told_saoirse": false,
  "told_cas": false,
  "told_noor": false,
  "told_idris": false,
  "told_arkwright": false,
  "told_tully": false,
  "morrow_knows": false,
  "relit_candle": false,
  "st_rowan": 0,
  "hurt_rowan": 0,
  "st_imogen": 0,
  "hurt_imogen": 0,
  "st_saoirse": 0,
  "hurt_saoirse": 0,
  "st_cas": 0,
  "hurt_cas": 0,
  "st_noor": 0,
  "hurt_noor": 0,
  "st_idris": 0,
  "hurt_idris": 0,
  "fr_toby": 0,
  "fr_kestrel": 0,
  "fr_bassani": 0,
  "fr_kovac": 0,
  "fr_rhys": 0,
  "fr_crook": 0,
  "fr_grey": 0,
  "fr_moth": 0,
  "fr_okoro": 0,
  "fr_holloway": 0,
  "fr_tully": 0,
  "fr_priya": 0,
  "fr_flick": 0,
  "fr_marcus": 0,
  "fr_hamish": 0,
  "fr_mina": 0,
  "fr_jonty": 0,
  "fr_odile": 0,
  "fr_jory": 0,
  "fr_arkwright": 0,
  "fr_nana": 0,
  "fr_dev": 0,
  "final_rel": "",
  "final_shape": "",
  "promise7": "",
  "kept7": false,
  "ember_with": "",
  "mask": "",
  "dance": "",
  "candle": "",
  "e01": false,
  "e02": false,
  "e03": false,
  "e04": false,
  "e05": false,
  "e06": false,
  "e07": false,
  "e08": false,
  "e09": false,
  "e10": false,
  "e11": false,
  "e12": false,
  "e13": false,
  "e14": false,
  "e15": false,
  "e16": false,
  "suspect": "",
  "accused_grey": false,
  "tully_fate": "",
  "know_heartfire": false,
  "know_morrow": false,
  "know_insider": false,
  "ch07_way": "",
  "ch09_way": "",
  "ch13_way": "",
  "order_offer": "",
  "toby_lit": false,
  "maisie_lit": false,
  "kit_lit": false,
  "odile_lit": false,
  "singers": 0,
  "plan22": "",
  "heartfire_choice": "",
  "saved_one": "",
  "ending": "",
  "house_lantern": "",
  "look_done": false,
  "b_rowan_lamp": false,
  "b_rowan_heat": false,
  "b_rowan_fire": false,
  "b_rowan_afraid": false,
  "b_rowan_want": false,
  "b_imogen_handbook": false,
  "b_imogen_study": false,
  "b_imogen_kit": false,
  "b_imogen_order": false,
  "b_imogen_want": false,
  "b_saoirse_bike": false,
  "b_saoirse_build": false,
  "b_saoirse_still": false,
  "b_saoirse_run": false,
  "b_saoirse_want": false,
  "b_cas_spar": false,
  "b_cas_kind": false,
  "b_cas_family": false,
  "b_cas_debt": false,
  "b_cas_want": false,
  "b_noor_sit": false,
  "b_noor_shift": false,
  "b_noor_carry": false,
  "b_noor_rest": false,
  "b_noor_want": false,
  "b_idris_saw": false,
  "b_idris_stacks": false,
  "b_idris_file": false,
  "b_idris_suspect": false,
  "b_idris_want": false
 },
 "clamp": {
  "nerve": [
   0,
   100
  ],
  "wit": [
   0,
   100
  ],
  "heart": [
   0,
   100
  ],
  "flame": [
   0,
   100
  ],
  "kindling": [
   0,
   100
  ],
  "chill": [
   0,
   3
  ],
  "pts_larkspire": [
   -500,
   5000
  ],
  "pts_owlcombe": [
   -500,
   5000
  ],
  "pts_heronmere": [
   -500,
   5000
  ],
  "pts_rookhallow": [
   -500,
   5000
  ],
  "st_rowan": [
   0,
   6
  ],
  "hurt_rowan": [
   0,
   2
  ],
  "st_imogen": [
   0,
   6
  ],
  "hurt_imogen": [
   0,
   2
  ],
  "st_saoirse": [
   0,
   6
  ],
  "hurt_saoirse": [
   0,
   2
  ],
  "st_cas": [
   0,
   6
  ],
  "hurt_cas": [
   0,
   2
  ],
  "st_noor": [
   0,
   6
  ],
  "hurt_noor": [
   0,
   2
  ],
  "st_idris": [
   0,
   6
  ],
  "hurt_idris": [
   0,
   2
  ],
  "fr_toby": [
   0,
   3
  ],
  "fr_kestrel": [
   0,
   3
  ],
  "fr_bassani": [
   0,
   3
  ],
  "fr_kovac": [
   0,
   3
  ],
  "fr_rhys": [
   0,
   3
  ],
  "fr_crook": [
   0,
   3
  ],
  "fr_grey": [
   0,
   3
  ],
  "fr_moth": [
   0,
   3
  ],
  "fr_okoro": [
   0,
   3
  ],
  "fr_holloway": [
   0,
   3
  ],
  "fr_tully": [
   0,
   3
  ],
  "fr_priya": [
   0,
   3
  ],
  "fr_flick": [
   0,
   3
  ],
  "fr_marcus": [
   0,
   3
  ],
  "fr_hamish": [
   0,
   3
  ],
  "fr_mina": [
   0,
   3
  ],
  "fr_jonty": [
   0,
   3
  ],
  "fr_odile": [
   0,
   3
  ],
  "fr_jory": [
   0,
   3
  ],
  "fr_arkwright": [
   0,
   3
  ],
  "fr_nana": [
   0,
   3
  ],
  "fr_dev": [
   0,
   3
  ]
 },
 "leads": [
  "rowan",
  "imogen",
  "saoirse",
  "cas",
  "noor",
  "idris"
 ],
 "houses": [
  "larkspire",
  "owlcombe",
  "heronmere",
  "rookhallow"
 ],
 "beats": {
  "rowan": [
   {
    "flag": "b_rowan_lamp",
    "stage": 2
   },
   {
    "flag": "b_rowan_heat",
    "stage": 3
   },
   {
    "flag": "b_rowan_fire",
    "stage": 4
   },
   {
    "flag": "b_rowan_afraid",
    "stage": 4
   },
   {
    "flag": "b_rowan_want",
    "stage": 5
   }
  ],
  "imogen": [
   {
    "flag": "b_imogen_handbook",
    "stage": 2
   },
   {
    "flag": "b_imogen_study",
    "stage": 3
   },
   {
    "flag": "b_imogen_kit",
    "stage": 4
   },
   {
    "flag": "b_imogen_order",
    "stage": 4
   },
   {
    "flag": "b_imogen_want",
    "stage": 5
   }
  ],
  "saoirse": [
   {
    "flag": "b_saoirse_bike",
    "stage": 2
   },
   {
    "flag": "b_saoirse_build",
    "stage": 3
   },
   {
    "flag": "b_saoirse_still",
    "stage": 4
   },
   {
    "flag": "b_saoirse_run",
    "stage": 4
   },
   {
    "flag": "b_saoirse_want",
    "stage": 5
   }
  ],
  "cas": [
   {
    "flag": "b_cas_spar",
    "stage": 2
   },
   {
    "flag": "b_cas_kind",
    "stage": 3
   },
   {
    "flag": "b_cas_family",
    "stage": 4
   },
   {
    "flag": "b_cas_debt",
    "stage": 4
   },
   {
    "flag": "b_cas_want",
    "stage": 5
   }
  ],
  "noor": [
   {
    "flag": "b_noor_sit",
    "stage": 2
   },
   {
    "flag": "b_noor_shift",
    "stage": 3
   },
   {
    "flag": "b_noor_carry",
    "stage": 4
   },
   {
    "flag": "b_noor_rest",
    "stage": 4
   },
   {
    "flag": "b_noor_want",
    "stage": 5
   }
  ],
  "idris": [
   {
    "flag": "b_idris_saw",
    "stage": 2
   },
   {
    "flag": "b_idris_stacks",
    "stage": 3
   },
   {
    "flag": "b_idris_file",
    "stage": 4
   },
   {
    "flag": "b_idris_suspect",
    "stage": 4
   },
   {
    "flag": "b_idris_want",
    "stage": 5
   }
  ]
 },
 "people": {
  "mc": {
   "cid": "MC",
   "name": "You",
   "age": 25,
   "kind": "student",
   "tier": "lead",
   "house": "",
   "romance": false,
   "appearance": "Chosen by the player: witch or wizard, and one of six skin tones. Hair and clothes neutral: a warm jumper and a practical coat, then Wrenfold robes in your house colours. Never shown in snapshots.",
   "status": [],
   "moods": [
    "neutral"
   ]
  },
  "rowan": {
   "cid": "C01",
   "name": "Rowan Ashby",
   "age": 26,
   "kind": "student",
   "tier": "lead",
   "house": "larkspire",
   "romance": true,
   "appearance": "Tall, broad-shouldered, open square face with a strong jaw and a slightly crooked nose (broken twice). Short copper-red hair, freckles everywhere, light skin that flushes easily. Warm brown eyes. Rolled-up sleeves, forearms with old burn-scar shine; Larkspire gold-and-rose scarf.",
   "status": [],
   "moods": [
    "neutral",
    "warm",
    "amused",
    "laugh",
    "tense",
    "hurt",
    "flare"
   ]
  },
  "imogen": {
   "cid": "C02",
   "name": "Imogen Sallow",
   "age": 24,
   "kind": "student",
   "tier": "lead",
   "house": "owlcombe",
   "romance": true,
   "appearance": "Slight, very upright, heart-shaped face with a sharp chin and quick dark eyes behind thin gold glasses. Black hair in a severe bob with a blunt fringe; light olive skin. A tailored plum waistcoat under her robes; ink on her fingers.",
   "status": [],
   "moods": [
    "neutral",
    "warm",
    "amused",
    "tense",
    "hurt",
    "attentive",
    "angry"
   ]
  },
  "saoirse": {
   "cid": "C03",
   "name": "Saoirse Maddock",
   "age": 28,
   "kind": "student",
   "tier": "lead",
   "house": "rookhallow",
   "romance": true,
   "appearance": "Wiry, angular, freckled face with a wide grin that shows a chipped front tooth. Wild dark-auburn curls tied up with a bootlace; pale skin with oil smudges. Grey-green eyes. A leather jacket over her robes, goggles pushed up on her head, copper Rookhallow pin.",
   "status": [],
   "moods": [
    "neutral",
    "warm",
    "amused",
    "laugh",
    "tense",
    "hurt"
   ]
  },
  "cas": {
   "cid": "C04",
   "name": "Casimir Drummond",
   "age": 27,
   "kind": "student",
   "tier": "lead",
   "house": "rookhallow",
   "romance": true,
   "appearance": "Tall and narrow, long elegant face with high cheekbones, a straight nose and a mouth set in a sneer by default. Pale blond hair swept back; very fair skin; cold grey eyes. Immaculate black robes with a copper-thread collar, a signet ring he turns when he's nervous.",
   "status": [],
   "moods": [
    "neutral",
    "warm",
    "amused",
    "tense",
    "hurt",
    "guarded"
   ]
  },
  "noor": {
   "cid": "C05",
   "name": "Noor Haddad",
   "age": 25,
   "kind": "student",
   "tier": "lead",
   "house": "heronmere",
   "romance": true,
   "appearance": "Medium height, soft oval face with strong dark brows and calm, heavy-lidded brown eyes. Long dark hair in a thick practical plait; warm light-brown skin. A navy nurse's watch pinned to her sea-green-and-pearl robes; sensible shoes.",
   "status": [],
   "moods": [
    "neutral",
    "warm",
    "amused",
    "tense",
    "hurt",
    "tired"
   ]
  },
  "idris": {
   "cid": "C06",
   "name": "Idris Penhallow",
   "age": 29,
   "kind": "student",
   "tier": "lead",
   "house": "owlcombe",
   "romance": true,
   "appearance": "Lean, long face with deep-set dark eyes, a strong nose and a neat short black beard. Close-cropped black hair; deep brown skin. Round wire glasses. Plum-and-silver second-year robes worn soft, a satchel stuffed with notebooks, a silver moth pin.",
   "status": [],
   "moods": [
    "neutral",
    "warm",
    "amused",
    "tense",
    "hurt",
    "attentive"
   ]
  },
  "toby": {
   "cid": "C07",
   "name": "Toby Quill",
   "age": 23,
   "kind": "student",
   "tier": "frequent",
   "house": "heronmere",
   "romance": false,
   "appearance": "Short and round-faced with pink cheeks, a snub nose and big anxious blue eyes. Floury-blond hair that sticks up at the crown; fair skin. A too-big knitted cardigan under his robes; flour on his sleeve.",
   "status": [
    {
     "date": "2027-03-06",
     "state": "hollowed",
     "note": "the Quiet",
     "until": "toby_lit"
    }
   ],
   "moods": [
    "neutral",
    "warm",
    "amused",
    "laugh",
    "scared",
    "sad",
    "hollowed"
   ]
  },
  "kestrel": {
   "cid": "C08",
   "name": "Imelda Kestrel",
   "age": 71,
   "kind": "staff",
   "tier": "frequent",
   "house": "",
   "romance": false,
   "appearance": "Tall, straight-backed old woman with a long lined face, bright hazel eyes and laughter lines. A silver braid to her waist, wound with a gold thread; brown freckled skin, star-freckles across the nose. Midnight-blue robes stitched with tiny gold wrens.",
   "status": [],
   "moods": [
    "neutral",
    "warm",
    "amused",
    "grave",
    "tired"
   ]
  },
  "bassani": {
   "cid": "C09",
   "name": "Aurelio Bassani",
   "age": 58,
   "kind": "staff",
   "tier": "supporting",
   "house": "larkspire",
   "romance": false,
   "appearance": "Round, theatrical, olive-skinned man with a magnificent curled grey moustache, bushy eyebrows and twinkling dark eyes. Bald on top with a grey fringe. Gold-and-rose waistcoat, a flower in his buttonhole that changes daily.",
   "status": [],
   "moods": [
    "neutral",
    "amused",
    "grave"
   ]
  },
  "kovac": {
   "cid": "C10",
   "name": "Vesna Kovač",
   "age": 49,
   "kind": "staff",
   "tier": "supporting",
   "house": "owlcombe",
   "romance": false,
   "appearance": "Thin, pale, angular face with sharp cheekbones and pale grey eyes that don't blink enough. Black hair with one white streak, pinned in a tight knot. High-necked plum robes, leather cuffs stained with potion.",
   "status": [],
   "moods": [
    "neutral",
    "attentive",
    "warm"
   ]
  },
  "rhys": {
   "cid": "C11",
   "name": "Mabli Rhys",
   "age": 52,
   "kind": "staff",
   "tier": "supporting",
   "house": "heronmere",
   "romance": false,
   "appearance": "Sturdy, weathered, rosy-cheeked woman with a broad smile and crinkled green eyes. Grey-streaked brown hair under a battered wide-brimmed hat with a live snail on it; ruddy white skin. Earth under her nails, sea-green apron.",
   "status": [],
   "moods": [
    "neutral",
    "warm"
   ]
  },
  "crook": {
   "cid": "C12",
   "name": "Tamsin Crook",
   "age": 44,
   "kind": "staff",
   "tier": "supporting",
   "house": "rookhallow",
   "romance": false,
   "appearance": "Wiry woman with a wry, lopsided face, a pipe in the corner of her mouth and one eyebrow permanently raised. Short cropped silver hair; dark brown skin. Copper earrings, black leather gauntlet on one arm for birds.",
   "status": [],
   "moods": [
    "neutral",
    "amused"
   ]
  },
  "grey": {
   "cid": "C13",
   "name": "Magnus Grey",
   "age": 55,
   "kind": "staff",
   "tier": "supporting",
   "house": "",
   "romance": false,
   "appearance": "Big, heavy, silent man with a craggy grey-stubbled face, a broken nose and deep-set tired blue eyes. Iron-grey hair cut short; pale weathered skin. Burn scars on both hands to the wrist; plain charcoal robes.",
   "status": [
    {
     "date": "2027-03-06",
     "state": "dead",
     "note": "holding the west stair in the Quiet"
    }
   ],
   "moods": [
    "neutral",
    "grave",
    "warm"
   ]
  },
  "moth": {
   "cid": "C14",
   "name": "Dunstan Moth",
   "age": 67,
   "kind": "staff",
   "tier": "supporting",
   "house": "",
   "romance": false,
   "appearance": "Tiny, delighted old man with a round pink face, enormous white eyebrows, huge round spectacles and a fluffy white beard. Stands on a stack of books to teach. Dusty lavender robes covered in chalk.",
   "status": [],
   "moods": [
    "neutral",
    "amused"
   ]
  },
  "solano": {
   "cid": "C15",
   "name": "Ines Solano",
   "age": 38,
   "kind": "staff",
   "tier": "minor",
   "house": "",
   "romance": false,
   "appearance": "Dreamy woman with a long face, heavy-lidded dark eyes and a faint smile. Long black hair loose with silver stars tangled in it; light brown skin. Night-blue shawl sewn with constellations.",
   "status": [],
   "moods": [
    "neutral"
   ]
  },
  "okoro": {
   "cid": "C16",
   "name": "Ferdie Okoro",
   "age": 34,
   "kind": "staff",
   "tier": "minor",
   "house": "",
   "romance": false,
   "appearance": "Athletic, cheerful man with a wide grin, a whistle in his teeth and a shaved head. Deep brown skin. Flight jacket with house-coloured patches, goggles around his neck.",
   "status": [],
   "moods": [
    "neutral",
    "amused"
   ]
  },
  "dunne": {
   "cid": "C17",
   "name": "Perpetua Dunne",
   "age": 80,
   "kind": "staff",
   "tier": "minor",
   "house": "",
   "romance": false,
   "appearance": "Ancient, birdlike librarian with a pinched face, sharp black eyes and a lace collar. White hair in a bun stuck with pencils; papery white skin. A chain of reading glasses round her neck.",
   "status": [],
   "moods": [
    "neutral"
   ]
  },
  "holloway": {
   "cid": "C18",
   "name": "Agnes Holloway",
   "age": 60,
   "kind": "staff",
   "tier": "minor",
   "house": "",
   "romance": false,
   "appearance": "Broad, brisk matron with a no-nonsense square face, apple cheeks and small shrewd eyes. Grey curls under a starched white cap; pink skin. Crisp white apron over pearl-grey robes.",
   "status": [],
   "moods": [
    "neutral"
   ]
  },
  "tully": {
   "cid": "C19",
   "name": "Absalom Tully",
   "age": 68,
   "kind": "staff",
   "tier": "frequent",
   "house": "",
   "romance": false,
   "appearance": "Stooped, gentle old man with a long kind face, a white walrus moustache and sad pale-blue eyes. Wisps of white hair under a flat cap; pink weathered skin. A patched brown coat, a long brass taper in his hand, oil on his fingers.",
   "status": [],
   "moods": [
    "neutral",
    "warm",
    "sad",
    "tense"
   ]
  },
  "priya": {
   "cid": "C20",
   "name": "Priya Menon",
   "age": 26,
   "kind": "student",
   "tier": "supporting",
   "house": "heronmere",
   "romance": false,
   "appearance": "Tall, graceful, long face with a wide smile and bright dark eyes. Glossy black hair in a high ponytail; medium brown skin. Sea-green robes with the sleeves pushed up, a violin case on her back.",
   "status": [],
   "moods": [
    "neutral",
    "warm"
   ]
  },
  "flick": {
   "cid": "C21",
   "name": "Felicity Barrow",
   "age": 30,
   "kind": "student",
   "tier": "supporting",
   "house": "larkspire",
   "romance": false,
   "appearance": "Brisk, sunny, round-faced woman with a turned-up nose and a clipboard. Blonde hair in two neat plaits; rosy white skin. Prefect's badge polished to a mirror.",
   "status": [],
   "moods": [
    "neutral",
    "amused"
   ]
  },
  "marcus": {
   "cid": "C22",
   "name": "Marcus Oduya",
   "age": 27,
   "kind": "student",
   "tier": "supporting",
   "house": "larkspire",
   "romance": false,
   "appearance": "Big, handsome, easy-grinning man with a strong jaw and a shaved fade. Dark brown skin. Glimmerball captain's jersey, broom over his shoulder.",
   "status": [],
   "moods": [
    "neutral",
    "amused"
   ]
  },
  "petra": {
   "cid": "C23",
   "name": "Petra Lindqvist",
   "age": 25,
   "kind": "student",
   "tier": "minor",
   "house": "owlcombe",
   "romance": false,
   "appearance": "Pale, cool, perfectly composed Scandinavian face with ice-blue eyes and white-blonde hair in a long braid. Silver cuff earrings.",
   "status": [],
   "moods": [
    "neutral"
   ]
  },
  "hamish": {
   "cid": "C24",
   "name": "Hamish Galbraith",
   "age": 29,
   "kind": "student",
   "tier": "supporting",
   "house": "rookhallow",
   "romance": false,
   "appearance": "Gangly, grinning second-year with a long freckled face, a ginger beard and wild ginger hair. Pale skin. Kilt under his robes, a ferret on his shoulder.",
   "status": [],
   "moods": [
    "neutral",
    "amused"
   ]
  },
  "delphine": {
   "cid": "C25",
   "name": "Delphine Arceneaux",
   "age": 31,
   "kind": "student",
   "tier": "minor",
   "house": "heronmere",
   "romance": false,
   "appearance": "Elegant woman with a long neck, fine features and dark amused eyes. Short natural hair dyed violet; deep brown skin. Sea-green second-year robes.",
   "status": [
    {
     "date": "2026-10-05",
     "state": "hollowed",
     "note": "found in the Glasshouses"
    }
   ],
   "moods": [
    "neutral",
    "hollowed"
   ]
  },
  "bram": {
   "cid": "C26",
   "name": "Bram Hollis",
   "age": 28,
   "kind": "student",
   "tier": "minor",
   "house": "rookhallow",
   "romance": false,
   "appearance": "Thickset, sullen young man with a heavy brow, small eyes and a buzz cut. Ruddy white skin. Rookhallow black robes worn untidily.",
   "status": [
    {
     "date": "2026-11-14",
     "state": "hollowed",
     "note": "found on the Rookery stairs"
    }
   ],
   "moods": [
    "neutral",
    "hollowed"
   ]
  },
  "mina": {
   "cid": "C27",
   "name": "Mina Achebe",
   "age": 24,
   "kind": "student",
   "tier": "supporting",
   "house": "owlcombe",
   "romance": false,
   "appearance": "Bright, fast-talking woman with a round face, huge headphones round her neck and gold hoop earrings. Braids piled high; dark brown skin. Plum robes covered in badges.",
   "status": [],
   "moods": [
    "neutral",
    "amused"
   ]
  },
  "jonty": {
   "cid": "C28",
   "name": "Jonty Farthing",
   "age": 30,
   "kind": "student",
   "tier": "minor",
   "house": "heronmere",
   "romance": false,
   "appearance": "Huge, gentle ex-rugby player with a bashed-in nose, cauliflower ear and a shy smile. Sandy hair; pink white skin. Knits during lessons.",
   "status": [],
   "moods": [
    "neutral"
   ]
  },
  "fitch": {
   "cid": "C29",
   "name": "Ptolemy Fitch",
   "age": 63,
   "kind": "row",
   "tier": "minor",
   "house": "",
   "romance": false,
   "appearance": "Thin, fussy clerk with a long nose, pince-nez, a quill behind each ear and a waistcoat covered in ink blots. Sparse grey hair combed over; sallow skin.",
   "status": [],
   "moods": [
    "neutral"
   ]
  },
  "odile": {
   "cid": "C30",
   "name": "Odile Pellow",
   "age": 46,
   "kind": "row",
   "tier": "supporting",
   "house": "",
   "romance": false,
   "appearance": "Striking woman with a strong face, dark knowing eyes and a wide mouth. Black curly hair shot with grey, tied in a scarf; olive skin. Leather apron with wand-wood shavings, a pencil through her bun.",
   "status": [
    {
     "date": "2026-12-05",
     "state": "hollowed",
     "note": "Thimble Cross high street"
    }
   ],
   "moods": [
    "neutral",
    "warm",
    "hollowed"
   ]
  },
  "hask": {
   "cid": "C31",
   "name": "Madame Hask",
   "age": 70,
   "kind": "row",
   "tier": "minor",
   "house": "",
   "romance": false,
   "appearance": "Small, sharp, elegant old woman with a pointed face, a mouthful of pins and a measuring tape round her neck that moves by itself. Silver bob; pale skin.",
   "status": [],
   "moods": [
    "neutral"
   ]
  },
  "tick": {
   "cid": "C32",
   "name": "Ambrose Tick",
   "age": 55,
   "kind": "row",
   "tier": "minor",
   "house": "",
   "romance": false,
   "appearance": "Round, bearded, twinkly man with bushy eyebrows and straw in his hair. Ruddy brown skin. A waistcoat with pockets full of something wriggling.",
   "status": [],
   "moods": [
    "neutral"
   ]
  },
  "arkwright": {
   "cid": "C33",
   "name": "Sabine Arkwright",
   "age": 47,
   "kind": "order",
   "tier": "supporting",
   "house": "",
   "romance": false,
   "appearance": "Hard, handsome woman with a scar through one eyebrow, a strong jaw and steady dark eyes. Close-cropped grey hair; brown skin. Long lamp-black greatcoat with a brass lamp badge.",
   "status": [],
   "moods": [
    "neutral",
    "grave"
   ]
  },
  "jory": {
   "cid": "C34",
   "name": "Jory Penrose",
   "age": 24,
   "kind": "order",
   "tier": "supporting",
   "house": "",
   "romance": false,
   "appearance": "Earnest young man with a boyish open face, big brown eyes and a nervous smile. Curly brown hair; light tan skin. A Lamplighter's greatcoat slightly too big for him.",
   "status": [],
   "moods": [
    "neutral",
    "tense"
   ]
  },
  "morrow": {
   "cid": "C35",
   "name": "Aldric Morrow",
   "age": 66,
   "kind": "choir",
   "tier": "frequent",
   "house": "",
   "romance": false,
   "appearance": "Tall, gaunt old man with a long, once-beautiful face gone grey as ash, sunken cheeks and pale colourless eyes. Long white hair; skin with a grey tint. Grey hooded robes, bare grey hands, a wick-shaped iron pendant.",
   "status": [],
   "moods": [
    "neutral",
    "hungry",
    "warm"
   ]
  },
  "corliss": {
   "cid": "C36",
   "name": "Corliss Fane",
   "age": 40,
   "kind": "choir",
   "tier": "minor",
   "house": "",
   "romance": false,
   "appearance": "Tall woman with a hood, a pale severe face, closed lips and eyes rimmed grey. Shaved head; pale skin. Grey robes. She never speaks; she hums.",
   "status": [],
   "moods": [
    "neutral"
   ]
  },
  "nana": {
   "cid": "C37",
   "name": "Nana Pearl",
   "age": 82,
   "kind": "ordinary",
   "tier": "supporting",
   "house": "",
   "romance": false,
   "appearance": "Tiny, sharp-eyed grandmother with a round face, a pouf of white hair, big red-framed glasses and pink lipstick. Warm brown skin (or matching the player: drawn to suit the six looks). Cardigan, pearls, slippers.",
   "status": [],
   "moods": [
    "neutral",
    "warm"
   ]
  },
  "dev": {
   "cid": "C38",
   "name": "Dev Mistry",
   "age": 26,
   "kind": "ordinary",
   "tier": "supporting",
   "house": "",
   "romance": false,
   "appearance": "Lanky, cheerful young man with a long face, big grin and messy black hair. Brown skin. A lanyard and a hoodie.",
   "status": [],
   "moods": [
    "neutral",
    "amused"
   ]
  },
  "moll": {
   "cid": "C40",
   "name": "Moll Dunmore",
   "age": 57,
   "kind": "village",
   "tier": "minor",
   "house": "",
   "romance": false,
   "appearance": "Huge, cheerful landlady with a red face, a booming laugh and brawny arms. Grey hair piled up; rosy white skin. Apron with the Crooked Lantern stitched on it.",
   "status": [],
   "moods": [
    "neutral"
   ]
  },
  "ombree": {
   "cid": "C41",
   "name": "Horace Ombree",
   "age": 74,
   "kind": "village",
   "tier": "minor",
   "house": "",
   "romance": false,
   "appearance": "Plump, dapper old sweetshop owner with a pink bald head, a waxed white moustache and a striped bow tie. Light brown skin.",
   "status": [],
   "moods": [
    "neutral"
   ]
  },
  "lettice": {
   "cid": "C42",
   "name": "Lettice Crane",
   "age": 25,
   "kind": "ghost",
   "tier": "minor",
   "house": "",
   "romance": false,
   "appearance": "A translucent young woman in 1980s school robes, with a round sweet face, big grey eyes and a frizzy perm. Silvery-blue and see-through.",
   "status": [],
   "moods": [
    "neutral"
   ]
  },
  "maisie": {
   "cid": "C43",
   "name": "Maisie Tully",
   "age": 30,
   "kind": "student",
   "tier": "minor",
   "house": "",
   "romance": false,
   "appearance": "Thin young woman with her father's long face and pale blue eyes gone foggy, fair hair in a hospital plait. Grey-tinged skin. A hospital cardigan.",
   "status": [
    {
     "date": "2020-11-01",
     "state": "hollowed",
     "note": "her Burning Year",
     "until": "maisie_lit"
    }
   ],
   "moods": [
    "hollowed",
    "neutral"
   ]
  },
  "kit": {
   "cid": "C44",
   "name": "Kit Sallow",
   "age": 27,
   "kind": "student",
   "tier": "minor",
   "house": "",
   "romance": false,
   "appearance": "Imogen's older brother: the same sharp chin and dark eyes, gone blank. Black hair grown out; light olive skin with a grey cast.",
   "status": [
    {
     "date": "2023-09-20",
     "state": "hollowed",
     "note": "his Burning Year",
     "until": "kit_lit"
    }
   ],
   "moods": [
    "hollowed"
   ]
  },
  "hester": {
   "cid": "C45",
   "name": "Hester Wren",
   "age": 60,
   "kind": "founder",
   "tier": "minor",
   "house": "",
   "romance": false,
   "appearance": "A painted portrait: a weather-beaten fisherwoman with a broad face, a crooked smile and bright wren-brown eyes. Grey hair in a knot; sunburnt white skin. Oilskin coat. Painted in oils, cracked varnish, gilt frame.",
   "status": [],
   "moods": [
    "neutral"
   ]
  },
  "honoria": {
   "cid": "C46",
   "name": "Honoria Drummond",
   "age": 88,
   "kind": "ordinary",
   "tier": "minor",
   "house": "",
   "romance": false,
   "appearance": "Formidable old woman with Cas's cheekbones, a hawk nose and cold pale eyes. White hair in an immaculate chignon; very fair skin. Black lace, jet beads.",
   "status": [],
   "moods": [
    "neutral"
   ]
  }
 },
 "places": {
  "P01": {
   "name": "7 Viaduct Street",
   "district": "Wrexley",
   "view": "home_kitchen"
  },
  "P02": {
   "name": "Nana Pearl's bungalow",
   "district": "Wrexley",
   "view": "nana_pearl"
  },
  "P03": {
   "name": "Your work",
   "district": "Wrexley",
   "view": "work"
  },
  "P05": {
   "name": "Lamplight Row",
   "district": "Lamplight Row",
   "view": "lamplight_row"
  },
  "P06": {
   "name": "The Wren's Nest",
   "district": "Lamplight Row",
   "view": "wrens_nest"
  },
  "P07": {
   "name": "Pellow & Daughters, Wandwrights",
   "district": "Lamplight Row",
   "view": "wand_shop"
  },
  "P08": {
   "name": "Hask & Needle",
   "district": "Lamplight Row",
   "view": "robe_shop"
  },
  "P09": {
   "name": "The Menagerie",
   "district": "Lamplight Row",
   "view": "menagerie"
  },
  "P10": {
   "name": "The Lamp & Ladle",
   "district": "Lamplight Row",
   "view": "lamp_ladle"
  },
  "P11": {
   "name": "Platform Nought",
   "district": "Kingsmere",
   "view": "platform_nought"
  },
  "P12": {
   "name": "Wrenfold Mere and the Boathouse",
   "district": "Wrenfold",
   "view": "mere_night"
  },
  "P13": {
   "name": "The Lantern Hall",
   "district": "Wrenfold",
   "view": "lantern_hall"
  },
  "P14": {
   "name": "Larkspire Tower",
   "district": "Wrenfold",
   "view": "larkspire"
  },
  "P15": {
   "name": "The Owlcombe Stacks",
   "district": "Wrenfold",
   "view": "owlcombe"
  },
  "P16": {
   "name": "The Heronmere Cloister",
   "district": "Wrenfold",
   "view": "heronmere"
  },
  "P17": {
   "name": "The Rookhallow Undercroft",
   "district": "Wrenfold",
   "view": "rookhallow"
  },
  "P18": {
   "name": "The Wordcraft Gallery",
   "district": "Wrenfold",
   "view": "classroom"
  },
  "P19": {
   "name": "The Brewing Cellars",
   "district": "Wrenfold",
   "view": "brewing_cellars"
  },
  "P20": {
   "name": "The Glasshouses",
   "district": "Wrenfold",
   "view": "glasshouses"
  },
  "P21": {
   "name": "The Observatory",
   "district": "Wrenfold",
   "view": "observatory"
  },
  "P22": {
   "name": "The Long Stacks",
   "district": "Wrenfold",
   "view": "library"
  },
  "P23": {
   "name": "The Warding Hall",
   "district": "Wrenfold",
   "view": "warding_hall"
  },
  "P24": {
   "name": "The Infirmary",
   "district": "Wrenfold",
   "view": "infirmary"
  },
  "P25": {
   "name": "The Weathervane Room",
   "district": "Wrenfold",
   "view": "weathervane_room"
  },
  "P26": {
   "name": "The Rookery",
   "district": "Wrenfold",
   "view": "rookery"
  },
  "P27": {
   "name": "The Glimmer Pitch",
   "district": "Wrenfold",
   "view": "glimmer_pitch"
  },
  "P28": {
   "name": "The Lanternwarden's Cottage",
   "district": "Wrenfold",
   "view": "tully_cottage"
  },
  "P29": {
   "name": "The Old Cloisters",
   "district": "Wrenfold",
   "view": "old_cloisters"
  },
  "P30": {
   "name": "The Heartfire Chamber",
   "district": "Wrenfold",
   "view": "heartfire"
  },
  "P31": {
   "name": "The Whispering Wood",
   "district": "Wrenfold",
   "view": "whispering_wood"
  },
  "P32": {
   "name": "Wrenfold's corridors",
   "district": "Wrenfold",
   "view": "corridor"
  },
  "P33": {
   "name": "The Kitchens",
   "district": "Wrenfold",
   "view": "kitchens"
  },
  "P34": {
   "name": "Thimble Cross",
   "district": "Thimble Cross",
   "view": "thimble_cross"
  },
  "P35": {
   "name": "Sugar & Sorcery",
   "district": "Thimble Cross",
   "view": "sweetshop"
  },
  "P36": {
   "name": "The Crooked Lantern",
   "district": "Thimble Cross",
   "view": "crooked_lantern"
  },
  "P37": {
   "name": "The Candlestones",
   "district": "Thimble Cross",
   "view": "candlestones"
  },
  "P38": {
   "name": "The Lamplighters' House",
   "district": "Kingsmere",
   "view": "lamplighters"
  },
  "P39": {
   "name": "St Ide's",
   "district": "Kingsmere",
   "view": "st_ides"
  },
  "P40": {
   "name": "The drowned chapel, Saltmarrow Fen",
   "district": "The Fen",
   "view": "fen_chapel"
  }
 },
 "views": [
  "home_kitchen",
  "home_street_night",
  "nana_pearl",
  "work",
  "lamplight_row",
  "wrens_nest",
  "wand_shop",
  "robe_shop",
  "menagerie",
  "lamp_ladle",
  "platform_nought",
  "mere_night",
  "mere_frozen",
  "mere_day",
  "boathouse",
  "lantern_hall",
  "lantern_hall_emberfall",
  "lantern_hall_longnight",
  "lantern_hall_dark",
  "larkspire",
  "owlcombe",
  "heronmere",
  "rookhallow",
  "classroom",
  "brewing_cellars",
  "glasshouses",
  "observatory",
  "library",
  "warding_hall",
  "infirmary",
  "weathervane_room",
  "rookery",
  "glimmer_pitch",
  "glimmer_pitch_snow",
  "tully_cottage",
  "old_cloisters",
  "heartfire",
  "whispering_wood",
  "corridor",
  "corridor_night",
  "kitchens",
  "thimble_cross",
  "thimble_cross_snow",
  "sweetshop",
  "crooked_lantern",
  "candlestones",
  "lamplighters",
  "st_ides",
  "fen_chapel"
 ],
 "evidence": {
  "e01": {
   "title": "A grey wick",
   "text": "Delphine's lantern was snuffed with a wick soaked in something grey that smells of marsh.",
   "essential": false
  },
  "e02": {
   "title": "Humming in the lanterns",
   "text": "The Choir's note travels through the lantern network: someone connected to the lanterns is letting it in.",
   "essential": false
  },
  "e03": {
   "title": "A ward opened from inside",
   "text": "The south ward-stone by the Glasshouses was unlocked from the castle side the night Delphine was taken.",
   "essential": false
  },
  "e04": {
   "title": "Marsh oil",
   "text": "The grey oil is Saltmarrow Fen lamp oil; the only store of it in Wrenfold is in the Lanternwarden's shed.",
   "essential": false
  },
  "e05": {
   "title": "Lettice Crane's warning",
   "text": "A ghost hollowed forty years ago: 'he's coming back for what he lost, and you have it.'",
   "essential": false
  },
  "e06": {
   "title": "Professor Grey's past",
   "text": "Grey spent six years inside the Grey Choir. (He was the Order's spy; this clue alone doesn't say so.)",
   "essential": false
  },
  "e07": {
   "title": "Bram's last argument",
   "text": "Bram Hollis quarrelled with Cas the night he was taken. (Cas was elsewhere; this clue alone doesn't say so.)",
   "essential": false
  },
  "e08": {
   "title": "The night rounds",
   "text": "Every hollowing fell on a night the Lanternwarden did the lantern round alone.",
   "essential": false
  },
  "e09": {
   "title": "Maisie Tully",
   "text": "Tully's daughter was hollowed in her Burning Year; he visits St Ide's every Sunday; someone has promised him something.",
   "essential": false
  },
  "e10": {
   "title": "The Heartfire",
   "text": "Hester Wren's own flame burns under the school; it lights every lantern and holds the wards.",
   "essential": true
  },
  "e11": {
   "title": "Morrow's school file",
   "text": "Aldric Morrow was a Kindler, snuffed in a Warding exercise forty years ago; the school hushed it up.",
   "essential": true
  },
  "e12": {
   "title": "Lucius Drummond's confession",
   "text": "Cas's grandfather cast the spell that snuffed Morrow, and was protected by the Deputy of the day.",
   "essential": false
  },
  "e13": {
   "title": "The Wren's Song",
   "text": "A counter-song against the Choir's note: it can't be sung alone, only by many voices together.",
   "essential": false
  },
  "e14": {
   "title": "Letters in the cottage",
   "text": "Morrow has written to Tully for three years, promising to relight Maisie.",
   "essential": false
  },
  "e15": {
   "title": "The boathouse way",
   "text": "An old passage runs from the boathouse under the Mere wall into the Old Cloisters.",
   "essential": false
  },
  "e16": {
   "title": "Midsummer",
   "text": "Morrow will come at the Midsummer Proving, when every lantern is lit and every student is in the Hall.",
   "essential": true
  }
 },
 "calendar": {
  "chapters": [
   {
    "id": "CH01",
    "title": "The Letter",
    "from": "2026-09-10",
    "to": "2026-09-11"
   },
   {
    "id": "CH02",
    "title": "Lamplight Row",
    "from": "2026-09-11",
    "to": "2026-09-11"
   },
   {
    "id": "CH03",
    "title": "The Lantern Hall",
    "from": "2026-09-11",
    "to": "2026-09-11"
   },
   {
    "id": "CH04",
    "title": "First Lessons",
    "from": "2026-09-14",
    "to": "2026-09-18"
   },
   {
    "id": "CH05",
    "title": "The Burning Year",
    "from": "2026-09-24",
    "to": "2026-09-26"
   },
   {
    "id": "CH06",
    "title": "The Hollowed Girl",
    "from": "2026-10-05",
    "to": "2026-10-07"
   },
   {
    "id": "CH07",
    "title": "An Evening Already Promised",
    "from": "2026-10-10",
    "to": "2026-10-11"
   },
   {
    "id": "CH08",
    "title": "Emberfall",
    "from": "2026-10-31",
    "to": "2026-11-01"
   },
   {
    "id": "CH09",
    "title": "Under Wrenfold",
    "from": "2026-11-04",
    "to": "2026-11-07"
   },
   {
    "id": "CH10",
    "title": "The Lamplighters",
    "from": "2026-11-14",
    "to": "2026-11-18"
   },
   {
    "id": "CH11",
    "title": "Thimble Cross",
    "from": "2026-12-05",
    "to": "2026-12-05"
   },
   {
    "id": "CH12",
    "title": "Longnight",
    "from": "2026-12-18",
    "to": "2026-12-22"
   },
   {
    "id": "CH13",
    "title": "Home Between",
    "from": "2026-12-23",
    "to": "2027-01-03"
   },
   {
    "id": "CH14",
    "title": "Candlewake",
    "from": "2027-01-30",
    "to": "2027-02-02"
   },
   {
    "id": "CH15",
    "title": "The Glimmer Cup",
    "from": "2027-02-13",
    "to": "2027-02-13"
   },
   {
    "id": "CH16",
    "title": "What the Founders Hid",
    "from": "2027-02-20",
    "to": "2027-02-27"
   },
   {
    "id": "CH17",
    "title": "The Quiet",
    "from": "2027-03-05",
    "to": "2027-03-07"
   },
   {
    "id": "CH18",
    "title": "The Lanternwarden",
    "from": "2027-03-10",
    "to": "2027-03-14"
   },
   {
    "id": "CH19",
    "title": "The Greening",
    "from": "2027-03-20",
    "to": "2027-03-22"
   },
   {
    "id": "CH20",
    "title": "The Wren's Song",
    "from": "2027-04-10",
    "to": "2027-04-24"
   },
   {
    "id": "CH21",
    "title": "Brightfire",
    "from": "2027-05-01",
    "to": "2027-05-02"
   },
   {
    "id": "CH22",
    "title": "Midsummer Eve",
    "from": "2027-06-20",
    "to": "2027-06-20"
   },
   {
    "id": "CH23",
    "title": "The Heartfire",
    "from": "2027-06-20",
    "to": "2027-06-21"
   },
   {
    "id": "CH24",
    "title": "The Last Lantern",
    "from": "2027-06-26",
    "to": "2028-06-26"
   }
  ],
  "parts": [
   {
    "id": "P1",
    "title": "Part One: Kindling",
    "chapters": [
     "CH01",
     "CH02",
     "CH03",
     "CH04",
     "CH05",
     "CH06",
     "CH07"
    ]
   },
   {
    "id": "P2",
    "title": "Part Two: Emberfall",
    "chapters": [
     "CH08",
     "CH09",
     "CH10",
     "CH11",
     "CH12"
    ]
   },
   {
    "id": "P3",
    "title": "Part Three: Deep Winter",
    "chapters": [
     "CH13",
     "CH14",
     "CH15",
     "CH16",
     "CH17",
     "CH18"
    ]
   },
   {
    "id": "P4",
    "title": "Part Four: The Greening",
    "chapters": [
     "CH19",
     "CH20",
     "CH21",
     "CH22",
     "CH23",
     "CH24"
    ]
   }
  ]
 },
 "endings": {
  "A": {
   "title": "The Heartfire Holds",
   "core": "The Wren's Song holds the Hall; you keep the Heartfire from Morrow; the Order takes him. The school stands, and you keep your flame."
  },
  "B": {
   "title": "Every Lantern Lit",
   "core": "You relight Morrow's own flame. He becomes a tired old man who can light a candle; the hollowed can be relit, slowly. It costs you most of your fire."
  },
  "C": {
   "title": "The Cold Hall",
   "core": "You let the Heartfire go out rather than let him take it. The wards fall; Wrenfold must move. Everyone lives."
  },
  "D": {
   "title": "The Last Lantern",
   "core": "You give your own flame to relight the Heartfire. Wrenfold stands. You go home to Wrexley without magic, remembering everything."
  },
  "E": {
   "title": "The Grey Road",
   "core": "You take the Heartfire yourself."
  },
  "F": {
   "title": "The Order's Oath",
   "core": "Morrow escapes into the Fen. You leave with the Lamplighters to hunt him."
  },
  "G_T": {
   "title": "What We Could Save: Toby",
   "core": "You couldn't stop him, only choose who came out of the root alive. Toby."
  },
  "G_M": {
   "title": "What We Could Save: Maisie",
   "core": "You couldn't stop him, only choose who came out of the root alive. Maisie Tully."
  },
  "G_K": {
   "title": "What We Could Save: the Headmistress",
   "core": "You couldn't stop him, only choose who came out of the root alive. Imelda Kestrel."
  },
  "H": {
   "title": "The Road Not Taken",
   "core": "You left before Midsummer. You read about it afterwards."
  }
 }
};
})(typeof window !== "undefined" ? window : globalThis);
