// Wrenfold: the cast. Ages at the opening (10 September). Appearance lines are the art direction for ChatGPT's portraits.
// kind: student | staff | order | choir | ordinary (no magic) | row (Lamplight Row trade) | village | ghost | founder
// tier: lead (romance route) | frequent | supporting | minor
// house: for students and heads of house
// status: dated changes the continuity checker enforces: hollowed (grey, blank, can't speak normally), dead, away.
//   A status can end ("until") when the story allows it (relighting): the script decides with a variable.
// moods: the portrait expressions to draw (neutral is always first).
"use strict";

const cast = [
  // ------------------------------------------------------------------ you
  { id: "MC", name: "You (name chosen)", age: 25, kind: "student", tier: "lead", home: "P01",
    appearance: "Chosen by the player: witch or wizard, and one of six skin tones. Hair and clothes neutral: a warm jumper and a practical coat, then Wrenfold robes in your house colours. Never shown in snapshots.",
    notes: "A Kindler: sees flames, can steady them, can relight them at a cost. Works an ordinary job in Wrexley (chosen). Raised by Nana Pearl." },

  // ------------------------------------------------------------------ the six (romance open to any player, entirely optional)
  { id: "C01", name: "Rowan Ashby", age: 26, kind: "student", tier: "lead", house: "larkspire", romance: true,
    appearance: "Tall, broad-shouldered, open square face with a strong jaw and a slightly crooked nose (broken twice). Short copper-red hair, freckles everywhere, light skin that flushes easily. Warm brown eyes. Rolled-up sleeves, forearms with old burn-scar shine; Larkspire gold-and-rose scarf.",
    notes: "Ex-firefighter; walked out of a burning house unburned. His flame comes out as heat. Big family in Wrexley's neighbour town. Afraid of himself.",
    moods: ["neutral", "warm", "amused", "laugh", "tense", "hurt", "flare"] },
  { id: "C02", name: "Imogen Sallow", age: 24, kind: "student", tier: "lead", house: "owlcombe", romance: true,
    appearance: "Slight, very upright, heart-shaped face with a sharp chin and quick dark eyes behind thin gold glasses. Black hair in a severe bob with a blunt fringe; light olive skin. A tailored plum waistcoat under her robes; ink on her fingers.",
    notes: "Law student; read the whole handbook on the train. Wants to join the Order. Brother Kit hollowed three years ago; she visits St Ide's monthly.",
    moods: ["neutral", "warm", "amused", "tense", "hurt", "attentive", "angry"] },
  { id: "C03", name: "Saoirse Maddock", age: 28, kind: "student", tier: "lead", house: "rookhallow", romance: true,
    appearance: "Wiry, angular, freckled face with a wide grin that shows a chipped front tooth. Wild dark-auburn curls tied up with a bootlace; pale skin with oil smudges. Grey-green eyes. A leather jacket over her robes, goggles pushed up on her head, copper Rookhallow pin.",
    notes: "Motorbike mechanic; kindled fixing an engine without touching it. Builds contraptions, breaks rules, never sits still.",
    moods: ["neutral", "warm", "amused", "laugh", "tense", "hurt"] },
  { id: "C04", name: "Casimir Drummond", age: 27, kind: "student", tier: "lead", house: "rookhallow", romance: true,
    appearance: "Tall and narrow, long elegant face with high cheekbones, a straight nose and a mouth set in a sneer by default. Pale blond hair swept back; very fair skin; cold grey eyes. Immaculate black robes with a copper-thread collar, a signet ring he turns when he's nervous.",
    notes: "Heir of an old magical family, disgraced by kindling late. Grandfather Lucius snuffed Aldric Morrow forty years ago. Lonely, sneering, secretly kind. House: Rookhallow unless the player is Rookhallow, in which case Owlcombe (the script uses cas_house).",
    moods: ["neutral", "warm", "amused", "tense", "hurt", "guarded"] },
  { id: "C05", name: "Noor Haddad", age: 25, kind: "student", tier: "lead", house: "heronmere", romance: true,
    appearance: "Medium height, soft oval face with strong dark brows and calm, heavy-lidded brown eyes. Long dark hair in a thick practical plait; warm light-brown skin. A navy nurse's watch pinned to her sea-green-and-pearl robes; sensible shoes.",
    notes: "A&E nurse; kindled mid-shift, stopping a bleed with her hands. Calm, dry, the one everyone calls. Bad at being looked after.",
    moods: ["neutral", "warm", "amused", "tense", "hurt", "tired"] },
  { id: "C06", name: "Idris Penhallow", age: 29, kind: "student", tier: "lead", house: "owlcombe", romance: true,
    appearance: "Lean, long face with deep-set dark eyes, a strong nose and a neat short black beard. Close-cropped black hair; deep brown skin. Round wire glasses. Plum-and-silver second-year robes worn soft, a satchel stuffed with notebooks, a silver moth pin.",
    notes: "Second-year Kindling scholar; studies the old Kindlers. The only one who sees what you are. Quiet, exact, secretive; half the school suspects him.",
    moods: ["neutral", "warm", "amused", "tense", "hurt", "attentive"] },

  // ------------------------------------------------------------------ your best friend
  { id: "C07", name: "Toby Quill", age: 23, kind: "student", tier: "frequent", house: "heronmere",
    appearance: "Short and round-faced with pink cheeks, a snub nose and big anxious blue eyes. Floury-blond hair that sticks up at the crown; fair skin. A too-big knitted cardigan under his robes; flour on his sleeve.",
    notes: "Baker's apprentice who kept setting croissants on fire. Your best friend. In love with Priya. Hollowed on 6 March; relit or not in CH19 (toby_lit).",
    status: [{ date: "2027-03-06", state: "hollowed", note: "the Quiet", until: "toby_lit" }],
    moods: ["neutral", "warm", "amused", "laugh", "scared", "sad", "hollowed"] },

  // ------------------------------------------------------------------ staff
  { id: "C08", name: "Imelda Kestrel", age: 71, kind: "staff", tier: "frequent",
    appearance: "Tall, straight-backed old woman with a long lined face, bright hazel eyes and laughter lines. A silver braid to her waist, wound with a gold thread; brown freckled skin, star-freckles across the nose. Midnight-blue robes stitched with tiny gold wrens.",
    notes: "Headmistress. Kindled at thirty. Knew Aldric Morrow at school. Hurt in the Quiet (March).",
    moods: ["neutral", "warm", "amused", "grave", "tired"] },
  { id: "C09", name: "Aurelio Bassani", age: 58, kind: "staff", tier: "supporting", house: "larkspire",
    appearance: "Round, theatrical, olive-skinned man with a magnificent curled grey moustache, bushy eyebrows and twinkling dark eyes. Bald on top with a grey fringe. Gold-and-rose waistcoat, a flower in his buttonhole that changes daily.",
    notes: "Deputy Head, Turning, head of Larkspire. Says everything twice, theatrically.", moods: ["neutral", "amused", "grave"] },
  { id: "C10", name: "Vesna Kovač", age: 49, kind: "staff", tier: "supporting", house: "owlcombe",
    appearance: "Thin, pale, angular face with sharp cheekbones and pale grey eyes that don't blink enough. Black hair with one white streak, pinned in a tight knot. High-necked plum robes, leather cuffs stained with potion.",
    notes: "Brewing, head of Owlcombe. Says nothing twice. Fair to the bone.", moods: ["neutral", "attentive", "warm"] },
  { id: "C11", name: "Mabli Rhys", age: 52, kind: "staff", tier: "supporting", house: "heronmere",
    appearance: "Sturdy, weathered, rosy-cheeked woman with a broad smile and crinkled green eyes. Grey-streaked brown hair under a battered wide-brimmed hat with a live snail on it; ruddy white skin. Earth under her nails, sea-green apron.",
    notes: "Herbwork, head of Heronmere. Earthy, kind, fiercely protective.", moods: ["neutral", "warm"] },
  { id: "C12", name: "Tamsin Crook", age: 44, kind: "staff", tier: "supporting", house: "rookhallow",
    appearance: "Wiry woman with a wry, lopsided face, a pipe in the corner of her mouth and one eyebrow permanently raised. Short cropped silver hair; dark brown skin. Copper earrings, black leather gauntlet on one arm for birds.",
    notes: "Beastlore, head of Rookhallow. Keeps a one-eyed griffin called Mrs Bellweather.", moods: ["neutral", "amused"] },
  { id: "C13", name: "Magnus Grey", age: 55, kind: "staff", tier: "supporting",
    appearance: "Big, heavy, silent man with a craggy grey-stubbled face, a broken nose and deep-set tired blue eyes. Iron-grey hair cut short; pale weathered skin. Burn scars on both hands to the wrist; plain charcoal robes.",
    notes: "Warding. Ex-Lamplighter who spied inside the Choir for years. Red herring; innocent. Dies in the Quiet, 6 March.",
    status: [{ date: "2027-03-06", state: "dead", note: "holding the west stair in the Quiet" }], moods: ["neutral", "grave", "warm"] },
  { id: "C14", name: "Dunstan Moth", age: 67, kind: "staff", tier: "supporting",
    appearance: "Tiny, delighted old man with a round pink face, enormous white eyebrows, huge round spectacles and a fluffy white beard. Stands on a stack of books to teach. Dusty lavender robes covered in chalk.",
    notes: "Wordcraft. Squeaks with joy at good spellwork.", moods: ["neutral", "amused"] },
  { id: "C15", name: "Ines Solano", age: 38, kind: "staff", tier: "minor",
    appearance: "Dreamy woman with a long face, heavy-lidded dark eyes and a faint smile. Long black hair loose with silver stars tangled in it; light brown skin. Night-blue shawl sewn with constellations.",
    notes: "Starreading. Always a little elsewhere; sometimes right.", moods: ["neutral"] },
  { id: "C16", name: "Ferdie Okoro", age: 34, kind: "staff", tier: "minor",
    appearance: "Athletic, cheerful man with a wide grin, a whistle in his teeth and a shaved head. Deep brown skin. Flight jacket with house-coloured patches, goggles around his neck.",
    notes: "Flight and Glimmerball coach. Former international Glimmer player.", moods: ["neutral", "amused"] },
  { id: "C17", name: "Perpetua Dunne", age: 80, kind: "staff", tier: "minor",
    appearance: "Ancient, birdlike librarian with a pinched face, sharp black eyes and a lace collar. White hair in a bun stuck with pencils; papery white skin. A chain of reading glasses round her neck.",
    notes: "Librarian of the Long Stacks. Knew Hester Wren's handwriting before she knew her own.", moods: ["neutral"] },
  { id: "C18", name: "Agnes Holloway", age: 60, kind: "staff", tier: "minor",
    appearance: "Broad, brisk matron with a no-nonsense square face, apple cheeks and small shrewd eyes. Grey curls under a starched white cap; pink skin. Crisp white apron over pearl-grey robes.",
    notes: "Matron of the Infirmary. Noor's ally and occasional nemesis.", moods: ["neutral"] },
  { id: "C19", name: "Absalom Tully", age: 68, kind: "staff", tier: "frequent",
    appearance: "Stooped, gentle old man with a long kind face, a white walrus moustache and sad pale-blue eyes. Wisps of white hair under a flat cap; pink weathered skin. A patched brown coat, a long brass taper in his hand, oil on his fingers.",
    notes: "The Lanternwarden: tends the ten thousand lanterns and knows every student's name. The insider. Daughter Maisie hollowed six years ago.",
    moods: ["neutral", "warm", "sad", "tense"] },

  // ------------------------------------------------------------------ students
  { id: "C20", name: "Priya Menon", age: 26, kind: "student", tier: "supporting", house: "heronmere",
    appearance: "Tall, graceful, long face with a wide smile and bright dark eyes. Glossy black hair in a high ponytail; medium brown skin. Sea-green robes with the sleeves pushed up, a violin case on her back.",
    notes: "Session violinist; plays for the Hall. Toby's crush.", moods: ["neutral", "warm"] },
  { id: "C21", name: "Felicity 'Flick' Barrow", age: 30, kind: "student", tier: "supporting", house: "larkspire",
    appearance: "Brisk, sunny, round-faced woman with a turned-up nose and a clipboard. Blonde hair in two neat plaits; rosy white skin. Prefect's badge polished to a mirror.",
    notes: "Larkspire prefect; ex-primary-school teacher. Bossy and kind.", moods: ["neutral", "amused"] },
  { id: "C22", name: "Marcus Oduya", age: 27, kind: "student", tier: "supporting", house: "larkspire",
    appearance: "Big, handsome, easy-grinning man with a strong jaw and a shaved fade. Dark brown skin. Glimmerball captain's jersey, broom over his shoulder.",
    notes: "Glimmerball captain; ex-semi-pro footballer.", moods: ["neutral", "amused"] },
  { id: "C23", name: "Petra Lindqvist", age: 25, kind: "student", tier: "minor", house: "owlcombe",
    appearance: "Pale, cool, perfectly composed Scandinavian face with ice-blue eyes and white-blonde hair in a long braid. Silver cuff earrings.",
    notes: "Imogen's rival for top of the year.", moods: ["neutral"] },
  { id: "C24", name: "Hamish Galbraith", age: 29, kind: "student", tier: "supporting", house: "rookhallow",
    appearance: "Gangly, grinning second-year with a long freckled face, a ginger beard and wild ginger hair. Pale skin. Kilt under his robes, a ferret on his shoulder.",
    notes: "Second-year prankster; Saoirse's partner in crime.", moods: ["neutral", "amused"] },
  { id: "C25", name: "Delphine Arceneaux", age: 31, kind: "student", tier: "minor", house: "heronmere",
    appearance: "Elegant woman with a long neck, fine features and dark amused eyes. Short natural hair dyed violet; deep brown skin. Sea-green second-year robes.",
    notes: "Heronmere second year. Hollowed in the Glasshouses, 5 October.",
    status: [{ date: "2026-10-05", state: "hollowed", note: "found in the Glasshouses" }], moods: ["neutral", "hollowed"] },
  { id: "C26", name: "Bram Hollis", age: 28, kind: "student", tier: "minor", house: "rookhallow",
    appearance: "Thickset, sullen young man with a heavy brow, small eyes and a buzz cut. Ruddy white skin. Rookhallow black robes worn untidily.",
    notes: "Cas's old crony, bully. Hollowed 14 November.",
    status: [{ date: "2026-11-14", state: "hollowed", note: "found on the Rookery stairs" }], moods: ["neutral", "hollowed"] },
  { id: "C27", name: "Mina Achebe", age: 24, kind: "student", tier: "supporting", house: "owlcombe",
    appearance: "Bright, fast-talking woman with a round face, huge headphones round her neck and gold hoop earrings. Braids piled high; dark brown skin. Plum robes covered in badges.",
    notes: "Runs Wrenfold Wireless, the school's illicit radio. Knows every rumour.", moods: ["neutral", "amused"] },
  { id: "C28", name: "Jonty Farthing", age: 30, kind: "student", tier: "minor", house: "heronmere",
    appearance: "Huge, gentle ex-rugby player with a bashed-in nose, cauliflower ear and a shy smile. Sandy hair; pink white skin. Knits during lessons.",
    notes: "Gentle giant; knits hats for everyone's familiars.", moods: ["neutral"] },

  // ------------------------------------------------------------------ Lamplight Row
  { id: "C29", name: "Ptolemy Fitch", age: 63, kind: "row", tier: "minor",
    appearance: "Thin, fussy clerk with a long nose, pince-nez, a quill behind each ear and a waistcoat covered in ink blots. Sparse grey hair combed over; sallow skin.",
    notes: "Wren's Nest welcome clerk. Ten thousand forms.", moods: ["neutral"] },
  { id: "C30", name: "Odile Pellow", age: 46, kind: "row", tier: "supporting",
    appearance: "Striking woman with a strong face, dark knowing eyes and a wide mouth. Black curly hair shot with grey, tied in a scarf; olive skin. Leather apron with wand-wood shavings, a pencil through her bun.",
    notes: "Wandwright. Hollowed at Thimble Cross, 5 December, singing the counter-song.",
    status: [{ date: "2026-12-05", state: "hollowed", note: "Thimble Cross high street" }], moods: ["neutral", "warm", "hollowed"] },
  { id: "C31", name: "Madame Hask", age: 70, kind: "row", tier: "minor",
    appearance: "Small, sharp, elegant old woman with a pointed face, a mouthful of pins and a measuring tape round her neck that moves by itself. Silver bob; pale skin.",
    notes: "Robe-maker at Hask & Needle.", moods: ["neutral"] },
  { id: "C32", name: "Ambrose Tick", age: 55, kind: "row", tier: "minor",
    appearance: "Round, bearded, twinkly man with bushy eyebrows and straw in his hair. Ruddy brown skin. A waistcoat with pockets full of something wriggling.",
    notes: "Keeper of the Menagerie.", moods: ["neutral"] },

  // ------------------------------------------------------------------ the Order of the Lamp
  { id: "C33", name: "Sabine Arkwright", age: 47, kind: "order", tier: "supporting",
    appearance: "Hard, handsome woman with a scar through one eyebrow, a strong jaw and steady dark eyes. Close-cropped grey hair; brown skin. Long lamp-black greatcoat with a brass lamp badge.",
    notes: "Commander of the Lamplighters. Brave, stretched thin, willing to use you as bait.", moods: ["neutral", "grave"] },
  { id: "C34", name: "Jory Penrose", age: 24, kind: "order", tier: "supporting",
    appearance: "Earnest young man with a boyish open face, big brown eyes and a nervous smile. Curly brown hair; light tan skin. A Lamplighter's greatcoat slightly too big for him.",
    notes: "Junior Lamplighter; moves you along on Lamplight Row. Keeps turning up.", moods: ["neutral", "tense"] },

  // ------------------------------------------------------------------ the Grey Choir
  { id: "C35", name: "Aldric Morrow", age: 66, kind: "choir", tier: "frequent",
    appearance: "Tall, gaunt old man with a long, once-beautiful face gone grey as ash, sunken cheeks and pale colourless eyes. Long white hair; skin with a grey tint. Grey hooded robes, bare grey hands, a wick-shaped iron pendant.",
    notes: "The last Kindler before you. Snuffed at school forty years ago; lives on stolen flames. Leads the Grey Choir. Wants the Heartfire, and you to carry it.",
    moods: ["neutral", "hungry", "warm"] },
  { id: "C36", name: "Corliss Fane", age: 40, kind: "choir", tier: "minor",
    appearance: "Tall woman with a hood, a pale severe face, closed lips and eyes rimmed grey. Shaved head; pale skin. Grey robes. She never speaks; she hums.",
    notes: "The Hush: Morrow's lieutenant. Only hums.", moods: ["neutral"] },

  // ------------------------------------------------------------------ home
  { id: "C37", name: "Nana Pearl", age: 82, kind: "ordinary", tier: "supporting",
    appearance: "Tiny, sharp-eyed grandmother with a round face, a pouf of white hair, big red-framed glasses and pink lipstick. Warm brown skin (or matching the player: drawn to suit the six looks). Cardigan, pearls, slippers.",
    notes: "Raised you. Lives across Wrexley. The only person you tell; she already knew something.", moods: ["neutral", "warm"] },
  { id: "C38", name: "Dev Mistry", age: 26, kind: "ordinary", tier: "supporting",
    appearance: "Lanky, cheerful young man with a long face, big grin and messy black hair. Brown skin. A lanyard and a hoodie.",
    notes: "Your friend and coworker from before. Covers for you. Never quite finds out.", moods: ["neutral", "amused"] },

  // ------------------------------------------------------------------ Thimble Cross
  { id: "C40", name: "Moll Dunmore", age: 57, kind: "village", tier: "minor",
    appearance: "Huge, cheerful landlady with a red face, a booming laugh and brawny arms. Grey hair piled up; rosy white skin. Apron with the Crooked Lantern stitched on it.",
    notes: "Landlady of the Crooked Lantern.", moods: ["neutral"] },
  { id: "C41", name: "Horace Ombree", age: 74, kind: "village", tier: "minor",
    appearance: "Plump, dapper old sweetshop owner with a pink bald head, a waxed white moustache and a striped bow tie. Light brown skin.",
    notes: "Sugar & Sorcery. Sells humming humbugs.", moods: ["neutral"] },

  // ------------------------------------------------------------------ the lost and the dead
  { id: "C42", name: "Lettice Crane", age: 25, kind: "ghost", tier: "minor",
    appearance: "A translucent young woman in 1980s school robes, with a round sweet face, big grey eyes and a frizzy perm. Silvery-blue and see-through.",
    notes: "Hollowed forty years ago (Morrow's classmate); died later. Walks on Emberfall and Midsummer.", moods: ["neutral"] },
  { id: "C43", name: "Maisie Tully", age: 30, kind: "student", tier: "minor",
    appearance: "Thin young woman with her father's long face and pale blue eyes gone foggy, fair hair in a hospital plait. Grey-tinged skin. A hospital cardigan.",
    notes: "Tully's daughter. Hollowed six years ago in her Burning Year. At St Ide's.",
    status: [{ date: "2020-11-01", state: "hollowed", note: "her Burning Year", until: "maisie_lit" }], moods: ["hollowed", "neutral"] },
  { id: "C44", name: "Kit Sallow", age: 27, kind: "student", tier: "minor",
    appearance: "Imogen's older brother: the same sharp chin and dark eyes, gone blank. Black hair grown out; light olive skin with a grey cast.",
    notes: "Hollowed three years ago. At St Ide's.",
    status: [{ date: "2023-09-20", state: "hollowed", note: "his Burning Year", until: "kit_lit" }], moods: ["hollowed"] },
  { id: "C45", name: "Hester Wren", age: 60, kind: "founder", tier: "minor",
    appearance: "A painted portrait: a weather-beaten fisherwoman with a broad face, a crooked smile and bright wren-brown eyes. Grey hair in a knot; sunburnt white skin. Oilskin coat. Painted in oils, cracked varnish, gilt frame.",
    notes: "The founder, four hundred years dead; her portrait in the Weathervane Room sometimes speaks.", moods: ["neutral"] },
  { id: "C46", name: "Honoria Drummond", age: 88, kind: "ordinary", tier: "minor",
    appearance: "Formidable old woman with Cas's cheekbones, a hawk nose and cold pale eyes. White hair in an immaculate chignon; very fair skin. Black lace, jet beads.",
    notes: "Cas's grandmother, Lucius's widow. Knows what Lucius did.", moods: ["neutral"] }
];

module.exports = { cast };
