#!/usr/bin/env node
// Writes docs/05-art-handoff.md: everything ChatGPT needs to draw for Wrenfold, generated from plan/ so it can't drift
// from the story. Portraits (every person × every expression the script uses), you (witch/wizard × six tones), the
// familiars, the places and their variants, the opening film, and the house crests.
//   node tools/art-handoff.js
"use strict";
const fs = require("fs");
const path = require("path");
const ROOT = path.resolve(__dirname, "..");
const { cast } = require(path.join(ROOT, "plan/cast.js"));
const { places, districts } = require(path.join(ROOT, "plan/places.js"));

const ID = { MC: "mc", C04: "cas", C08: "kestrel", C09: "bassani", C10: "kovac", C11: "rhys", C12: "crook", C13: "grey", C14: "moth",
  C15: "solano", C16: "okoro", C17: "dunne", C18: "holloway", C19: "tully", C21: "flick", C29: "fitch", C30: "odile", C31: "hask",
  C32: "tick", C33: "arkwright", C35: "morrow", C36: "corliss", C37: "nana", C40: "moll", C41: "ombree", C43: "maisie", C44: "kit",
  C45: "hester", C46: "honoria" };
const slug = (s) => s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/[^a-z]/g, "");
const idOf = (c) => ID[c.id] || slug(c.name.split(" ")[0]);

// the moods the script actually uses, per person, so nothing is drawn that never appears (and nothing used is missing)
const used = {};
const dir = path.join(ROOT, "js/story/scenes");
for (const f of fs.readdirSync(dir).filter((f) => /^ch\d\d\.js$/.test(f))) {
  for (const m of fs.readFileSync(path.join(dir, f), "utf8").matchAll(/@([a-z]+):([a-z]+)/g)) (used[m[1]] = used[m[1]] || new Set()).add(m[2]);
}

const MOOD_NOTES = {
  neutral: "resting face, the default", warm: "a soft real smile", amused: "a wry or delighted grin", laugh: "laughing, eyes creased",
  tense: "worried, jaw set", hurt: "wounded, eyes down", attentive: "listening hard, head slightly tilted", angry: "furious",
  guarded: "closed, wary", tired: "exhausted", sad: "grieving", scared: "frightened", grave: "serious, heavy news",
  flare: "flame surging: eyes lit gold from inside, a heat-haze round the head", hollowed: "hollowed: grey-tinged skin, eyes like fogged glass, a polite empty half-smile (same face, not a monster)",
  hungry: "the hunger: gaunt, eyes too bright", ghost: "translucent silver-blue", small: "small and shy"
};

let out = `# Wrenfold — art handoff for ChatGPT

*Generated by \`node tools/art-handoff.js\` from the plan and the script, so it always matches the story. Everything here is new; nothing is reused from Calder.*

## Style

- **The same family as Calder's art**: painted pixel art, 16-bit-era detail, hand-placed pixels, limited palette per image, soft dithering in gradients, no vector smoothness. Warm, storybook, a little melancholy.
- **The feel**: merry, wondrous, candlelit (the Lantern Hall's floating lanterns are the signature image), with a real dark edge (the Grey Choir: grey hoods, humming, colour drained).
- **Portraits**: head and shoulders, three-quarter or front view, on a **transparent background**, 1122 × 1402 masters (4:5) are ideal; the game exports them to 256 × 320. Same framing for everyone: top of the head near the top, shoulders at the bottom edge. Students wear their house colours (Larkspire gold and rose; Owlcombe plum and silver; Heronmere sea-green and pearl; Rookhallow black and copper). Expressions keep the **same face and outfit**, only the expression changes.
- **Places**: 16:9, 1672 × 941 masters are ideal; the game exports 640 × 360. No people in them unless noted (the story adds portraits).
- **Files**: name them exactly as listed and put them in \`art/masters/portraits/\`, \`art/masters/environments/\` and \`art/masters/cinematic/\`. \`python3 tools/import-art.py\` does the rest.

## 1. You (the player)

Twelve portraits: **witch** and **wizard**, each in six skin tones. Mid-twenties, friendly, an ordinary face that could be anyone's; a warm jumper under an open plain black robe (the house lining shows as a thin neutral grey, so it works for every house). Hair: shoulder-length and soft for the witch, short and a bit untidy for the wizard, dark brown for the lighter tones and black for the darker ones. Neutral expression only.

| File | Look |
|---|---|
`;
const tones = [["porcelain", "very pale, cool pink undertone"], ["fair", "fair, warm"], ["olive", "light olive"], ["tan", "golden tan"], ["brown", "medium brown"], ["deep", "deep brown"]];
for (const form of ["witch", "wizard"]) for (const [t, d] of tones) out += `| \`mc-${form}-${t}.png\` | ${form}, ${d} skin |\n`;

out += `
## 2. Familiars

One portrait each, same 4:5 framing, the animal filling the frame warmly, on a transparent background. Chosen by the player in Chapter 2; shown when it's named and whenever it does something.

| File | Familiar |
|---|---|
| \`fam-cat.png\` | a small black cat with coin-gold eyes |
| \`fam-owl.png\` | a barn owl, pale heart-shaped face |
| \`fam-hare.png\` | a big brown hare with black-tipped ears and amber eyes |
| \`fam-fox.png\` | a young fox kit, russet and white, one black-socked paw |
| \`fam-raven.png\` | a glossy raven, one eye catching the light |
| \`fam-toad.png\` | a fat, magnificently green toad with golden eyes |
| \`fam-moth.png\` | a luna moth the size of a hand, pale green, faintly glowing, long tails on its wings |
| \`fam-ferret.png\` | a cream-and-brown ferret with a bandit mask |

## 3. The cast

Each person's **appearance line** is the brief. Draw every expression listed; the list is taken from the script (expressions marked *(planned)* aren't in the written chapters yet but will be).

`;
const tierOrder = { lead: 0, frequent: 1, supporting: 2, minor: 3 };
const people = cast.filter((c) => c.id !== "MC").sort((a, b) => tierOrder[a.tier] - tierOrder[b.tier] || a.id.localeCompare(b.id));
let count = 0;
for (const c of people) {
  const id = idOf(c);
  const planned = c.moods || ["neutral"];
  const inScript = used[id] || new Set();
  const all = [...new Set(["neutral", ...planned, ...inScript])];
  const num = c.id.slice(1);
  out += `### ${c.name.replace(/ '[^']+'/, "")} (${c.id}, ${c.tier}${c.house ? ", " + c.house : ""})\n\n${c.appearance}\n\n`;
  for (const m of all) {
    count++;
    const note = MOOD_NOTES[m] || m;
    out += `- \`c${num.padStart(2, "0")}-${id}-${m}.png\`: ${note}${inScript.has(m) || m === "neutral" ? "" : " *(planned)*"}\n`;
  }
  out += "\n";
}

out += `## 4. Places

Each place has a main picture and, where the story needs them, variants (a season, a festival, a darker night). **${places.length} places.**

| File | Place | Brief |
|---|---|---|
`;
let views = 0;
for (const p of places) {
  if (p.view) { out += `| \`${p.view.replace(/_/g, "-")}.png\` | ${p.name} (${districts[p.district]}) | ${p.notes} |\n`; views++; }
  for (const v of p.variants || []) {
    const hint = { home_street_night: "Viaduct Street at night in the rain, the viaduct overhead, one lit window", mere_frozen: "the Mere frozen white under stars, the castle lit, lanterns on the ice (Longnight, Candlewake)", mere_day: "the Mere on a bright autumn day, boats at the jetty", boathouse: "the old boathouse inside: lantern-boats on the black water, a stone stair up into the rock",
      lantern_hall_emberfall: "the Hall at Emberfall: every lantern burning red and orange, masks, apple-fire", lantern_hall_longnight: "the Hall at Longnight midnight: every lantern burning blue, snow at the great window, the Dance", lantern_hall_dark: "the Hall in the Quiet: the lanterns guttering grey, shadows, broken tables",
      glimmer_pitch_snow: "the Glimmer Pitch in February snow, hoops of lanterns glowing through falling snow", corridor_night: "a castle corridor at night: lanterns turned low, moonlight in long bars, a sleeping portrait", thimble_cross_snow: "Thimble Cross high street in deep December snow, lit shop windows" }[v] || "variant";
    out += `| \`${v.replace(/_/g, "-")}.png\` | ${p.name}, variant | ${hint} |\n`; views++;
  }
}

// ---------------------------------------------------------------- 5. the film, with the storyboard folded in
const board = fs.readFileSync(path.join(ROOT, "docs/04-intro-storyboard.md"), "utf8");
const shots = board.slice(board.indexOf("## The shots"), board.indexOf("## Handover")).replace("## The shots", "").trim();
out += `
## 5. The opening film (pixel-art animation)

A Stardew-Valley-style opening: about 67 seconds, 11 shots, played the first time you press **Begin** (skippable, replayable from the menu). The full storyboard is \`docs/04-intro-storyboard.md\`; my rough concept frames for composition are in \`art/concept/intro-01.png\` … \`intro-11.png\` (the game plays those until yours arrive).

**How it's built.** The game animates by sliding **layers** at different speeds (parallax) and by swapping **frames**. So for each shot, draw either one still (\`intro-NN.png\`) or a set of transparent layers (\`intro-NN-sky.png\`, \`intro-NN-town.png\` …), all the same canvas size (640 × 360, or a 1920 × 1080 master). Where a shot has a small looping motion (the fox, the steam, the flame), draw the extra frames as \`intro-NN-<layer>-f1.png\`, \`-f2.png\` … and I'll play them in order. No text in any image. The player is never seen from the front.

${shots}

### Animation frames wanted, shot by shot

| Shot | Files | Notes |
|---|---|---|
| 1 | \`intro-01-sky.png\`, \`intro-01-clouds.png\` | clouds layer wider than the frame (960 px) so it can drift; 2–3 star twinkle frames optional (\`intro-01-sky-f1..f3\`) |
| 2 | \`intro-02-sky\`, \`-hills\`, \`-town\`, \`-viaduct\`, \`-train\` | the **train** is a separate strip with lit windows, about 200 × 24 px, on transparent; town layer 960 px wide for the pan |
| 3 | \`intro-03-street\`, \`-fox\`, \`-rain\` | **fox**: 4 frames (sitting, ear flick, head turning, looking at you); **rain**: 3 frames of diagonal streaks, tileable |
| 4 | \`intro-04.png\` | one still; optional 2-frame laptop-screen flicker |
| 5 | \`intro-05.png\` + \`intro-05-bulb-f1..f2\`, \`intro-05-steam-f1..f4\`, \`intro-05-candle-f1..f3\` | bulb on/off; kettle steam curling; candle flame leaning towards the viewer |
| 6 | \`intro-06.png\`, \`intro-06-envelope.png\` | envelope separate, on transparent, faint gold edge glow; 2-frame glow pulse optional |
| 7 | \`intro-07.png\` | hands and blank parchment; the game types the letter on it |
| 8 | \`intro-08.png\`, \`intro-08-line.png\` | the gold doorway outline as its own transparent layer (the game reveals it); 4 frames of the wallpaper rippling (\`intro-08-wall-f1..f4\`) |
| 9 | \`intro-09-kitchen\`, \`-you\`, \`-beyond\` | **beyond** = Lamplight Row through the arch; 3-frame warm light pulse optional |
| 10 | \`intro-10-glow\`, \`intro-10-lanterns\` | lanterns layer 360 px **taller** than the frame so it can rise; or a lantern sprite sheet (see §10) |
| 11 | \`intro-11.png\` (+ optional \`intro-11-lanterns\`) | also the title screen; leave the upper third of sky clear for the title |
`;

// ---------------------------------------------------------------- 6. chapter cards
const { chapters } = require(path.join(ROOT, "plan/calendar.js"));
const CARD = {
  CH01: "Your kitchen at 11:58 pm, from behind: the letter on the mat, the doorway beginning to glow in the wall.",
  CH02: "Lamplight Row at night: crooked gables, lamps in every colour, a bus-shelter door standing open onto it.",
  CH03: "The Lantern Hall on the first night: ten thousand paper lanterns drifting under a roof you can't see; one lantern burning white.",
  CH04: "The Wordcraft Gallery: rows of candles all lit at once, a tiny professor on a stack of books, astonished.",
  CH05: "A castle corridor at night; one snuffed candle on a sconce, and a bare hand reaching for it.",
  CH06: "The Glasshouses at dawn, rain on the glass; a girl in sea-green sitting very still among the ferns.",
  CH07: "The Glimmer pitch at dusk: stands on stilts over the shallows, lantern-hoops in the air, a glowing ball.",
  CH08: "Emberfall: the Hall's lanterns burning red; masks; hundreds of lanterns floating out on the black Mere.",
  CH09: "Under Wrenfold: the Old Cloisters, carved wrens on every pillar, a sealed door, a faint figure of light.",
  CH10: "The Rookery tower at dawn: hundreds of familiars on perches, a spiral stair, a black crow sitting very still.",
  CH11: "Thimble Cross in the snow: crooked high street, market cross, a striped wand-stall; the snowflakes hanging frozen in the air.",
  CH12: "Longnight: the Lantern Hall in frost-white, snow falling from the roof and stopping a foot above the dancers.",
  CH13: "Viaduct Street at night under the railway arches, streetlights going grey one by one.",
  CH14: "Candlewake: a river of candles crossing the frozen Mere in the blue dark before dawn.",
  CH15: "The Glimmer pitch in snow: one lantern-hoop gone dead grey among the gold.",
  CH16: "A small brown leather journal with a tooled wren, open by a fire, a sheet of five-line music beside it.",
  CH17: "The Quiet: the Heronmere cloister at night, the iron lake door standing open, grey light, a hare alone on the stones.",
  CH18: "The Lanternwarden's cottage by the boathouse: lamp over the door, photographs on every wall, a stove drawer open.",
  CH19: "The Greening: the Winter Garden glasshouse thrown open, rows of seeds in black soil, spring light.",
  CH20: "Five sheets of music with a wren, a lark, an owl, a heron and a rook drawn at the top, spread on a library table.",
  CH21: "Brightfire: a great bonfire in a ring of standing stones on a hill, sparks rising into a violet May sky.",
  CH22: "Midsummer Eve: the Lantern Hall with every lantern lit, and one white lantern at the very top.",
  CH23: "The Heartfire: a flame the size of a person hanging in a black rock cave, threads of light rising from it like harp strings.",
  CH24: "The last lantern: one paper lantern rising alone into a summer night sky over the Mere."
};
out += `
## 6. Chapter title cards (24)

Shown full-width when each chapter begins, with the chapter number and title set by the game (no text in the art). 16:9, same style and size as the places (1672 × 941 masters, exported to 640 × 360). Put them in \`art/masters/cards/\`. Until they exist, the game borrows a place picture for each.

| File | Chapter | Picture |
|---|---|---|
`;
for (const ch of chapters) if (CARD[ch.id]) out += `| \`${ch.id.toLowerCase()}.png\` | ${ch.id.slice(2)}. ${ch.title} | ${CARD[ch.id]} |\n`;

// ---------------------------------------------------------------- 7. ending cards
const { endings } = require(path.join(ROOT, "plan/endings.js"));
const END = {
  A: "The Lantern Hall at dawn, every lantern gold, one white one at the top; students asleep on the benches.",
  B: "An old man's thin hands cupping a single small blue candle flame, in a dark window.",
  C: "The castle across the Mere completely dark; a line of hand-held candles coming down the lawn at dawn.",
  D: "A small terraced-house kitchen, yellow light, a white candle in a jam jar on the table, a kettle that isn't boiling.",
  E: "A lone figure on a hilltop among standing stones, burning with every colour at once; every candle in the valley below leaning towards them.",
  F: "The Fen at dusk: reeds, black water, a drowned chapel tower, a lamp on a boat, and a grey figure far off on a causeway.",
  G_T: "The jetty at dawn: a round-faced young man asleep under a blanket, a brown hare beside him, the castle's lanterns burning low and blue.",
  G_M: "The Lanternwarden's cottage door: a young woman lighting the lamp over it with her bare hand, her father watching.",
  G_K: "The Weathervane Room: maps of the Fen pinned over every wall, a white-haired woman at the window.",
  H: "A newspaper folded on a windowsill on the Fen, a letter on top, rain on the glass."
};
out += `
## 7. Ending cards (10)

Shown on the ending screen. Same size and style as the chapter cards; put them in \`art/masters/cards/\`.

| File | Ending | Picture |
|---|---|---|
`;
for (const e of endings) out += `| \`end-${e.id}.png\` | ${e.name} | ${END[e.id] || e.core} |\n`;

// ---------------------------------------------------------------- 8. snapshots (illustrated moments)
const SNAPS = [
  ["doorway", "CH01", "You, from behind, one hand on the frame of a glowing arched doorway in a kitchen wall; Lamplight Row beyond."],
  ["wandshop", "CH02", "Pellow & Daughters: ladders, drawers to the ceiling, a woman with a pencil in her bun holding out a wand; glowing shavings."],
  ["nesting", "CH03", "The first night: one paper lantern burning white, rising out of cupped hands towards ten thousand gold ones."],
  ["candle", "CH05", "A corridor at night: a hand on a snuffed candle, the wick catching white; a bearded man in round glasses half-hidden at the corner."],
  ["emberfall", "CH08", "Masks and lanterns on the black Mere at night; the castle glowing red behind; a translucent girl in old school robes by the water."],
  ["rookery", "CH10", "The Rookery stair at dawn: a grey young man sitting on a step, a crow pressed to his neck, hundreds of screaming birds above."],
  ["odile", "CH11", "Thimble Cross in the snow: a woman in a leather apron singing, boots planted, in front of six huddled students; grey hooded figures coming down the hill; snowflakes frozen in the air."],
  ["longnight", "CH12", "Midnight on Longnight: the Hall's lanterns rippling from gold to deep blue, dancers looking up, snow hanging in the air."],
  ["candlewake", "CH14", "Two figures stopped in the middle of the frozen Mere at dawn, candles in their hands, the procession flowing round them."],
  ["hoop", "CH15", "A snowy Glimmer pitch: a lantern-hoop gone dead grey, a big man in gold and rose falling from his broom."],
  ["toby", "CH17", "The Heronmere cloister: a round young man in jam-stained pyjamas singing, wand shaking, in front of frightened first-years; grey hoods in the green light."],
  ["stair", "CH17", "A narrow spiral stair: a scarred man in dark robes holding it with his bare hands, a shimmer of heat round them, six grey hoods below."],
  ["maisie", "CH18", "St Ide's: a pale young woman in a pink cardigan by a tall window, an old man in a flat cap holding her hand, daffodils."],
  ["choir", "CH20", "The Old Cloisters full of students with candles, singing; carved wrens on the pillars; a small black door glowing at the end."],
  ["brightfire", "CH21", "Two figures among standing stones at night, the bonfire behind them, the lake and the lit castle below."],
  ["song", "CH22", "The Lantern Hall ringing: hundreds singing, lanterns flaring back to gold from one white lantern at the top."],
  ["heartfire", "CH23", "A gaunt grey old man with long white hair before the Heartfire, a figure facing him from the cave mouth."],
  ["ghosts", "CH23", "Midsummer dawn: silvery ghosts walking home across the Mere towards the sun; one tall man looking back."]
];
out += `
## 8. Illustrated moments (snapshots, 18)

Full-width pictures shown at the story's biggest moments and kept in the journal. 16:9, same size as places, people drawn in (in the pixel style, small enough that faces are suggestion). Put them in \`art/masters/snapshots/\`, named exactly as below. The story plays a place picture in their slot until they exist.

| File | Chapter | The moment |
|---|---|---|
`;
SNAPS.forEach(([slot, ch, text], i) => { out += `| \`snap-${String(i + 1).padStart(2, "0")}-${slot}.png\` | ${ch.slice(2)} | ${text} |\n`; });

// ---------------------------------------------------------------- 9. crests, title and icons
out += `
## 9. Crests, title and icons

- \`crest-larkspire.png\`, \`crest-owlcombe.png\`, \`crest-heronmere.png\`, \`crest-rookhallow.png\`: a lark, an owl, a heron, a rook, each on a small shield in the house colours, pixel style, transparent, 256 × 256.
- \`crest-wrenfold.png\`: the school crest: a cocked-tailed wren in the middle, the four birds at the corners.
- \`icon.png\`: the app and browser icon, 512 × 512: the red wax seal with the wren, pixel style, readable at 32 × 32.
- \`seal.png\`: the wax wren seal on its own, transparent, 128 × 128 (the invitation letter and the save screen use it).
- The **title screen** uses film shot 11.

## 10. Animated loops (optional, and lovely)

Small sprite animations the game can play over pictures. Each is a horizontal strip of frames on a transparent background; frame size given. Nice to have, not needed to ship.

| File | Frames | Size per frame | What |
|---|---|---|---|
| \`anim-lantern.png\` | 8 | 32 × 48 | one paper lantern drifting and turning, candle flicker inside (tinted by the game for house colours; draw it warm gold) |
| \`anim-lantern-white.png\` | 8 | 32 × 48 | the same, burning white (yours) |
| \`anim-candle.png\` | 6 | 24 × 48 | a candle flame flickering |
| \`anim-heartfire.png\` | 8 | 160 × 200 | the Heartfire turning slowly through every colour |
| \`anim-hum.png\` | 6 | 640 × 360 | grey ripples washing across the frame (the Choir's hum), transparent |
| \`anim-snow.png\` | 4 | 640 × 360 | falling snow, tileable |
| \`anim-rain.png\` | 3 | 640 × 360 | rain streaks, tileable |
| \`anim-ghost.png\` | 4 | 64 × 96 | a translucent silver-blue figure shimmering |
| \`anim-fam-<kind>.png\` | 4 | 64 × 64 | an idle loop for each familiar (cat, owl, hare, fox, raven, toad, moth, ferret): blink, ear flick, feather ruffle, wing twitch |
`;

// ---------------------------------------------------------------- totals
out += `
## Where to put everything

| Folder | What |
|---|---|
| \`art/masters/portraits/\` | you, the familiars, the cast (§1–3) |
| \`art/masters/environments/\` | places and variants (§4) |
| \`art/masters/cinematic/\` | the film: stills, layers and frames (§5) |
| \`art/masters/cards/\` | chapter and ending cards (§6–7) |
| \`art/masters/snapshots/\` | illustrated moments (§8) |
| \`art/masters/ui/\` | crests, icon, seal, animated loops (§9–10) |

Then \`python3 tools/import-art.py\` exports them all to game size.

## Totals

- You: 12 portraits · familiars: 8 · the cast: ${people.length} people, ${count} expressions · places: ${views} pictures
- Film: 11 shots (plus layers and loop frames) · chapter cards: 24 · ending cards: ${endings.length} · illustrated moments: ${SNAPS.length}
- Crests: 5 · icon and seal: 2 · animated loops: 9 kinds (optional)
`;

fs.writeFileSync(path.join(ROOT, "docs/05-art-handoff.md"), out);
console.log(`wrote docs/05-art-handoff.md: ${people.length} people, ${count} portrait files, ${views} place pictures`);
