#!/usr/bin/env node
// Writes docs/05-art-handoff.md: everything ChatGPT needs to draw for Wrenfold, generated from plan/ so it can't drift
// from the story. Portraits (every person × every expression the script uses), you (witch/wizard × six tones), the
// familiars, the places and their variants, the opening film, and the house crests.
//   node tools/art-handoff.js
"use strict";
const fs = require("fs");
const path = require("path");
const ROOT = path.resolve(__dirname, "..");
const { cast } = require(path.join(ROOT, "plan/cast.js"));
const { places, districts } = require(path.join(ROOT, "plan/places.js"));

const ID = { MC: "mc", C04: "cas", C08: "kestrel", C09: "bassani", C10: "kovac", C11: "rhys", C12: "crook", C13: "grey", C14: "moth",
  C15: "solano", C16: "okoro", C17: "dunne", C18: "holloway", C19: "tully", C21: "flick", C29: "fitch", C30: "odile", C31: "hask",
  C32: "tick", C33: "arkwright", C35: "morrow", C36: "corliss", C37: "nana", C40: "moll", C41: "ombree", C43: "maisie", C44: "kit",
  C45: "hester", C46: "honoria" };
const slug = (s) => s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/[^a-z]/g, "");
const idOf = (c) => ID[c.id] || slug(c.name.split(" ")[0]);

// the moods the script actually uses, per person, so nothing is drawn that never appears (and nothing used is missing)
const used = {};
const dir = path.join(ROOT, "js/story/scenes");
for (const f of fs.readdirSync(dir).filter((f) => /^ch\d\d\.js$/.test(f))) {
  for (const m of fs.readFileSync(path.join(dir, f), "utf8").matchAll(/@([a-z]+):([a-z]+)/g)) (used[m[1]] = used[m[1]] || new Set()).add(m[2]);
}

const MOOD_NOTES = {
  neutral: "resting face, the default", warm: "a soft real smile", amused: "a wry or delighted grin", laugh: "laughing, eyes creased",
  tense: "worried, jaw set", hurt: "wounded, eyes down", attentive: "listening hard, head slightly tilted", angry: "furious",
  guarded: "closed, wary", tired: "exhausted", sad: "grieving", scared: "frightened", grave: "serious, heavy news",
  flare: "flame surging: eyes lit gold from inside, a heat-haze round the head", hollowed: "hollowed: grey-tinged skin, eyes like fogged glass, a polite empty half-smile (same face, not a monster)",
  hungry: "the hunger: gaunt, eyes too bright", ghost: "translucent silver-blue", small: "small and shy"
};

let out = `# Wrenfold — art handoff for ChatGPT

*Generated by \`node tools/art-handoff.js\` from the plan and the script, so it always matches the story. Everything here is new; nothing is reused from Calder.*

## Style

- **The same family as Calder's art**: painted pixel art, 16-bit-era detail, hand-placed pixels, limited palette per image, soft dithering in gradients, no vector smoothness. Warm, storybook, a little melancholy.
- **The feel**: merry, wondrous, candlelit (the Lantern Hall's floating lanterns are the signature image), with a real dark edge (the Grey Choir: grey hoods, humming, colour drained).
- **Portraits**: head and shoulders, three-quarter or front view, on a **transparent background**, 1122 × 1402 masters (4:5) are ideal; the game exports them to 256 × 320. Same framing for everyone: top of the head near the top, shoulders at the bottom edge. Students wear their house colours (Larkspire gold and rose; Owlcombe plum and silver; Heronmere sea-green and pearl; Rookhallow black and copper). Expressions keep the **same face and outfit**, only the expression changes.
- **Places**: 16:9, 1672 × 941 masters are ideal; the game exports 640 × 360. No people in them unless noted (the story adds portraits).
- **Files**: name them exactly as listed and put them in \`art/masters/portraits/\`, \`art/masters/environments/\` and \`art/masters/cinematic/\`. \`python3 tools/import-art.py\` does the rest.

## 1. You (the player)

Twelve portraits: **witch** and **wizard**, each in six skin tones. Mid-twenties, friendly, an ordinary face that could be anyone's; a warm jumper under an open plain black robe (the house lining shows as a thin neutral grey, so it works for every house). Hair: shoulder-length and soft for the witch, short and a bit untidy for the wizard, dark brown for the lighter tones and black for the darker ones. Neutral expression only.

| File | Look |
|---|---|
`;
const tones = [["porcelain", "very pale, cool pink undertone"], ["fair", "fair, warm"], ["olive", "light olive"], ["tan", "golden tan"], ["brown", "medium brown"], ["deep", "deep brown"]];
for (const form of ["witch", "wizard"]) for (const [t, d] of tones) out += `| \`mc-${form}-${t}.png\` | ${form}, ${d} skin |\n`;

out += `
## 2. Familiars

One portrait each, same 4:5 framing, the animal filling the frame warmly, on a transparent background. Chosen by the player in Chapter 2; shown when it's named and whenever it does something.

| File | Familiar |
|---|---|
| \`fam-cat.png\` | a small black cat with coin-gold eyes |
| \`fam-owl.png\` | a barn owl, pale heart-shaped face |
| \`fam-hare.png\` | a big brown hare with black-tipped ears and amber eyes |
| \`fam-fox.png\` | a young fox kit, russet and white, one black-socked paw |
| \`fam-raven.png\` | a glossy raven, one eye catching the light |
| \`fam-toad.png\` | a fat, magnificently green toad with golden eyes |
| \`fam-moth.png\` | a luna moth the size of a hand, pale green, faintly glowing, long tails on its wings |
| \`fam-ferret.png\` | a cream-and-brown ferret with a bandit mask |

## 3. The cast

Each person's **appearance line** is the brief. Draw every expression listed; the list is taken from the script (expressions marked *(planned)* aren't in the written chapters yet but will be).

`;
const tierOrder = { lead: 0, frequent: 1, supporting: 2, minor: 3 };
const people = cast.filter((c) => c.id !== "MC").sort((a, b) => tierOrder[a.tier] - tierOrder[b.tier] || a.id.localeCompare(b.id));
let count = 0;
for (const c of people) {
  const id = idOf(c);
  const planned = c.moods || ["neutral"];
  const inScript = used[id] || new Set();
  const all = [...new Set(["neutral", ...planned, ...inScript])];
  const num = c.id.slice(1);
  out += `### ${c.name.replace(/ '[^']+'/, "")} (${c.id}, ${c.tier}${c.house ? ", " + c.house : ""})\n\n${c.appearance}\n\n`;
  for (const m of all) {
    count++;
    const note = MOOD_NOTES[m] || m;
    out += `- \`c${num.padStart(2, "0")}-${id}-${m}.png\`: ${note}${inScript.has(m) || m === "neutral" ? "" : " *(planned)*"}\n`;
  }
  out += "\n";
}

out += `## 4. Places

Each place has a main picture and, where the story needs them, variants (a season, a festival, a darker night). **${places.length} places.**

| File | Place | Brief |
|---|---|---|
`;
let views = 0;
for (const p of places) {
  if (p.view) { out += `| \`${p.view.replace(/_/g, "-")}.png\` | ${p.name} (${districts[p.district]}) | ${p.notes} |\n`; views++; }
  for (const v of p.variants || []) {
    const hint = { home_street_night: "Viaduct Street at night in the rain, the viaduct overhead, one lit window", mere_frozen: "the Mere frozen white under stars, the castle lit, lanterns on the ice (Longnight, Candlewake)", mere_day: "the Mere on a bright autumn day, boats at the jetty", boathouse: "the old boathouse inside: lantern-boats on the black water, a stone stair up into the rock",
      lantern_hall_emberfall: "the Hall at Emberfall: every lantern burning red and orange, masks, apple-fire", lantern_hall_longnight: "the Hall at Longnight midnight: every lantern burning blue, snow at the great window, the Dance", lantern_hall_dark: "the Hall in the Quiet: the lanterns guttering grey, shadows, broken tables",
      glimmer_pitch_snow: "the Glimmer Pitch in February snow, hoops of lanterns glowing through falling snow", corridor_night: "a castle corridor at night: lanterns turned low, moonlight in long bars, a sleeping portrait", thimble_cross_snow: "Thimble Cross high street in deep December snow, lit shop windows" }[v] || "variant";
    out += `| \`${v.replace(/_/g, "-")}.png\` | ${p.name}, variant | ${hint} |\n`; views++;
  }
}

out += `
## 5. The opening film

The storyboard is \`docs/04-intro-storyboard.md\`: 11 shots, with parallax layers named there (\`intro-01-sky.png\` and so on, transparent PNGs, 640 × 360 or a 1920 × 1080 master). My rough concept frames for composition are in \`art/concept/\`. Put finished frames in \`art/masters/cinematic/\`.

## 6. House crests and the title

- \`crest-larkspire.png\`, \`crest-owlcombe.png\`, \`crest-heronmere.png\`, \`crest-rookhallow.png\`: a lark, an owl, a heron, a rook, each on a small shield in the house colours, pixel style, transparent, 256 × 256.
- \`crest-wrenfold.png\`: the school crest: a cocked-tailed wren in the middle, the four birds at the corners.
- The **title screen** uses film shot 11 (the castle at night under lanterns).

## Totals

- You: 12 portraits · familiars: 8 · the cast: ${people.length} people, ${count} expressions · places: ${views} pictures · film: 11 shots (plus layers) · crests: 5.
`;

fs.writeFileSync(path.join(ROOT, "docs/05-art-handoff.md"), out);
console.log(`wrote docs/05-art-handoff.md: ${people.length} people, ${count} portrait files, ${views} place pictures`);
