#!/usr/bin/env node
// Generates js/story/sandbox-world.js: what Sandbox mode tells Claude about Wrenfold. The story bible (docs/01-story.md),
// the cast with their script ids, the places with their notes and the picture each one uses, and the moods a portrait
// can show. Regenerate after changing the plan or the bible.
//   node tools/gen-sandbox.js
"use strict";
const fs = require("fs");
const path = require("path");
const ROOT = path.resolve(__dirname, "..");
const P = (f) => require(path.join(ROOT, "plan", f));
const { cast } = P("cast.js");
const { places, districts } = P("places.js");

const slug = (s) => s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();
const OVERRIDE = { MC: "mc", C18: "orrell" };

// the picture each place uses in the written story: its most common *place view
const counts = {};
const sceneDir = path.join(ROOT, "js", "story", "scenes");
for (const f of fs.readdirSync(sceneDir)) {
  const s = fs.readFileSync(path.join(sceneDir, f), "utf8");
  for (const m of s.matchAll(/^\s*\*place (P\d\d) (\w+)\s*$/gm)) {
    const c = (counts[m[1]] = counts[m[1]] || {});
    c[m[2]] = (c[m[2]] || 0) + 1;
  }
}
const placeViews = {};
for (const [pid, c] of Object.entries(counts)) placeViews[pid] = Object.entries(c).sort((a, b) => b[1] - a[1])[0][0];

const people = cast.filter((c) => c.id !== "MC").map((c) => ({
  id: OVERRIDE[c.id] || slug(c.name.split(" ")[0]),
  name: c.name.replace(/ \(.*\)$/, ""),
  age: c.age, kind: c.kind, tier: c.tier, knows: c.knows || "",
  look: (c.appearance || "").slice(0, 220),
  limits: (c.limits || []).join("; ")
}));

const placeList = places.map((p) => ({
  id: p.id, name: p.name, district: districts[p.district] || p.district,
  notes: (p.notes || "").replace(/\s*C\d\d(, C\d\d)*\.?\s*$/, ""),
  view: placeViews[p.id] || null
}));

const bible = fs.readFileSync(path.join(ROOT, "docs", "01-story.md"), "utf8")
  .replace(/\n## What's kept from Nuit Blanche[\s\S]*$/, "");

const out = { bible, people, places: placeList,
  moods: ["neutral", "attentive", "amused", "laugh", "warm", "shy", "tense", "scared", "angry", "hurt", "sad", "guarded", "surprised", "tired", "small", "moon", "hungry", "returned"] };
const file = path.join(ROOT, "js", "story", "sandbox-world.js");
fs.writeFileSync(file, "/* Generated by tools/gen-sandbox.js. */\n(function (root) { (root.NB || (root.NB = {})).SANDBOX_WORLD = " +
  JSON.stringify(out) + "; })(typeof window !== \"undefined\" ? window : globalThis);\n");
console.log("wrote", path.relative(ROOT, file), (fs.statSync(file).size / 1024).toFixed(0) + " KB,", people.length, "people,", placeList.length, "places,", Object.keys(placeViews).length, "with pictures");
