#!/usr/bin/env node
// Generates js/story/plan-data.js from plan/ so the game and the checked plan share one source of truth:
// variables (with defaults and clamps), people, places, evidence, the calendar, routes and endings.
//   node tools/gen-config.js
"use strict";
const fs = require("fs");
const path = require("path");
const ROOT = path.resolve(__dirname, "..");
const P = (f) => require(path.join(ROOT, "plan", f));
const opt = (f, d) => { try { return P(f); } catch (e) { if (e.code === "MODULE_NOT_FOUND") return d; throw e; } };
const { vars, LEADS, HOUSES } = P("state.js");
const { cast } = P("cast.js");
const { places, districts } = P("places.js");
const { evidence } = opt("evidence.js", { evidence: [] });
const cal = P("calendar.js");
const { endings } = opt("endings.js", { endings: [] });
const { routes } = opt("routes.js", { routes: [] });

// script ids: first name, except where the story calls someone by another name
const ID = { MC: "mc", C04: "cas", C08: "kestrel", C09: "bassani", C10: "kovac", C11: "rhys", C12: "crook", C13: "grey", C14: "moth",
  C15: "solano", C16: "okoro", C17: "dunne", C18: "holloway", C19: "tully", C21: "flick", C29: "fitch", C30: "odile", C31: "hask",
  C32: "tick", C33: "arkwright", C35: "morrow", C36: "corliss", C37: "nana", C40: "moll", C41: "ombree", C43: "maisie", C44: "kit",
  C45: "hester", C46: "honoria" };
const slug = (s) => s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/[^a-z]/g, "");
const idOf = (c) => ID[c.id] || slug(c.name.split(" ")[0]);
const people = {};
for (const c of cast) {
  const id = idOf(c);
  if (people[id]) throw new Error("duplicate person id " + id);
  people[id] = { cid: c.id, name: c.name.replace(/ \(.*\)$/, "").replace(/ '[^']+'/, ""), age: c.age, kind: c.kind, tier: c.tier, house: c.house || "",
    romance: !!c.romance, appearance: c.appearance || "", status: c.status || [], moods: c.moods || ["neutral"] };
}

const startVars = {}, clamp = {};
for (const [k, d] of Object.entries(vars)) {
  startVars[k] = d.default;
  if (d.type !== "number") continue;
  if (/^st_/.test(k)) clamp[k] = [0, 6];
  else if (/^fr_/.test(k)) clamp[k] = [0, 3];
  else if (/^hurt_/.test(k)) clamp[k] = [0, 2];
  else if (["nerve", "wit", "heart", "flame", "kindling"].includes(k)) clamp[k] = [0, 100];
  else if (k === "chill") clamp[k] = [0, 3];
  else if (/^pts_/.test(k)) clamp[k] = [-500, 5000];
}
for (const r of routes) for (const b of r.beats) if (!(b.flag in startVars)) startVars[b.flag] = false;
const beats = Object.fromEntries(routes.map((r) => [r.lead, r.beats.map((b) => ({ flag: b.flag, stage: b.stage }))]));

const views = fs.existsSync(path.join(ROOT, "art/places")) ? fs.readdirSync(path.join(ROOT, "art/places")).filter((f) => f.endsWith(".png")).map((f) => f.replace(/\.png$/, "").replace(/-/g, "_")) : [];
// every view the plan names is legal in the script, drawn or not (the game shows a placeholder until the art arrives)
for (const p of places) for (const v of [p.view].concat(p.variants || [])) if (v && !views.includes(v)) views.push(v);

const data = {
  startVars, clamp, leads: LEADS, houses: HOUSES, beats, people,
  places: Object.fromEntries(places.map((p) => [p.id, { name: p.name, district: districts[p.district], view: p.view || "" }])),
  views,
  evidence: Object.fromEntries(evidence.map((e) => [e.id, { title: e.name, text: e.establishes, essential: !!e.essential }])),
  calendar: { chapters: cal.chapters.map((c) => ({ id: c.id, title: c.title, from: c.from, to: c.to })), parts: cal.parts },
  endings: Object.fromEntries(endings.map((e) => [e.id, { title: e.name, core: e.core }]))
};

const out = "/* Wrenfold — generated by tools/gen-config.js from plan/. Do not edit by hand. */\n" +
  "(function (root) {\n  \"use strict\";\n  var NB = root.NB || (root.NB = {});\n  NB.plan = " + JSON.stringify(data, null, 1) + ";\n})(typeof window !== \"undefined\" ? window : globalThis);\n";
fs.mkdirSync(path.join(ROOT, "js/story"), { recursive: true });
fs.writeFileSync(path.join(ROOT, "js/story/plan-data.js"), out);
console.log(`wrote js/story/plan-data.js: ${Object.keys(startVars).length} variables, ${Object.keys(people).length} people, ${places.length} places, ${views.length} views, ${evidence.length} clues`);
